### ISSUE TITLE
warpimage does not work in celestial coordinates

### ISSUE THREAD

**Issue by ycopin** [matplotlib/basemap#101]
Basemap.warpimage does not work when in celestial coordinates (see bottom panel on attached image).

Test script available from https://gist.github.com/ycopin/5012663

![bug_hammer](https://f.cloud.github.com/assets/812050/184533/336f1738-7cdf-11e2-968b-e109d5e9f1a4.png)

**Comment by WeatherGod** [comment]
Basemap now rases a ValueError for this example, stating that warpimage does not work with celestial coordinates. Closing.
