### ISSUE TITLE
weird contour plot with polar projections

### ISSUE THREAD

**Issue by bssrdf** [matplotlib/basemap#118]
Hi

I am making Polar Stereographic Projection maps of some climate model outputs. For some of these data, the plot looks weird. For example, in this figure
(https://dl.dropboxusercontent.com/u/45427012/ALB_ERR.png), only two color contours showed up while the actual data should span much wider range. Furthermore, a large portion of the region should be blank since the data are masked out by netcdf module already (they are undefined). 
You can find the script and dataset which generated the figure at here

python script
https://dl.dropboxusercontent.com/u/45427012/plot_albice_error.py

data (netcdf4), you'll need netcdf module to open it.
https://dl.dropboxusercontent.com/u/45427012/alb.nc4

BTW,  I am using basemap-1.0.6 with matplotlib-1.2.1 on py2.7.

Any help will be much appreciated.

Bin Zhao

**Comment by WeatherGod** [comment]
Closing the issue since there has been no follow-up (assumed that the advice was valid).
