### ISSUE TITLE
drawmeridians/parallels label text color not changeable

### ISSUE THREAD

**Issue by neothemachine** [matplotlib/basemap#145]
In the docs of `drawparallels` it says that any other `**kwargs` are supplied to `ax.text`. The problem is that `ax.text` has a `color` parameter which I need to set somehow. But `color` is also a regular keyword of `drawparallels` which means that it won't get there.

I really, really, really don't want to use something like `mpl.rcParams['text.color'] = colors.textcolor`.

**Comment by WeatherGod** [comment]
This was manually merged into master, and so GitHub never closed this issue automatically. Closing now.
