### ISSUE TITLE
Limb (map boundary) color is not set if round=True

### ISSUE THREAD

**Issue by neothemachine** [matplotlib/basemap#160]
In `drawmapboundary` the line/edge color of the limb is set in all cases except in the `round=True` case. This should not be.

The following is probably the problematic line:
```python
            limb = Circle((0.5*(self.xmax+self.xmin),0.5*(self.ymax+self.ymin)),
                    radius=0.5*(self.xmax-self.xmin),fc='none')
```

**Comment by WeatherGod** [comment]
I have a fix for this (and similar issues) in PR #291.
