### ISSUE TITLE
Additional map data (e.g. tetonic plate boundaries)

### ISSUE THREAD

**Issue by megies** [matplotlib/basemap#167]
We're currently thinking about adding additional background map data in our seismological project (obspy/obspy#921). One thing would be tectonic plate boundaries. As we currently use basemap for map plots we could instead add some functionality that might be useful to a wider audience right here at basemap.

Any thoughts?

**Comment by mankoff** [comment]
Seems like it shouldn't be a part of Basemap itself, but a separate package (or part of obspy) that can easily be installed and used. There are an infinite number of maps. I wouldn't want to see them all, or even a fraction, in core basemap...

**Comment by megies** [comment]
Alright, thanks for the feedback, we'll be adding it at obspy then. Closing..
