### ISSUE TITLE
Clarify Python 3 support?

### ISSUE THREAD

**Issue by cdeil** [matplotlib/basemap#176]
Does the latest basemap release 1.0.7 support Python 3?

It's not clear to me from the PyPI page:
https://pypi.python.org/pypi/basemap/1.0.7

In your current `setup.py` I see that it's supported ... maybe you could also mention it explicitly here where you say "Python 2.5 or higher"?
https://github.com/matplotlib/basemap#requirements

I'm asking because I'm using Python 3 via Macports and basemap is not available for Python 3 there.

**Comment by cdeil** [comment]
Found a Macports issue discussing Python 3 support for basemap:
https://trac.macports.org/ticket/45584

**Comment by tacaswell** [comment]
Yes, anaconda has a built version of it.  

Your question seems to mostly be if macports supports it which it outside of our scope.

**Comment by cdeil** [comment]
@tacaswell My main question was if that latest released `basemap 1.0.7` supports Python 3.4 ... I gather the answer is "yes".
