### ISSUE TITLE
PIL v.s Pillow

### ISSUE THREAD

**Issue by HughP** [matplotlib/basemap#177]
It seems that PIL, the graphics library dependency is dead (or near dead) and modern development is on [Pillow](https://github.com/python-pillow/Pillow). I am new to the Python landscape. So I [asked over at homebrew](https://github.com/Homebrew/homebrew-python/issues/204) if there might be a brew for PIL but evidently not. I am just wondering if there is a way to force basemap to use Pillow instead of PIL. Several of the functions fail saying they need PIL, but others work.

**Comment by jenshnielsen** [comment]
As far as I know pillow should be mostly a drop in replacement for PIL. You can install pillow and every thing should be fine.

http://pillow.readthedocs.org/porting-pil-to-pillow.html 
The only changes needed should be to ensure that Image is imported from PIL ands that `_imaging` is not imported.  I can't find any occurrences of these in the Basemap code so I think the only thing left to do is to ensure that the documentation is up to data.

**Comment by mdboom** [comment]
matplotlib itself has supported Pillow for some time.

**Comment by WeatherGod** [comment]
"Several of the functions fail saying they need PIL, but others work."

It would help to know which ones fail, and what their tracebacks are.

**Comment by HughP** [comment]
Which ones work (**or don't work**)? I have tried the robinson projection and plotting a dataset, [following this tutorial](http://introtopython.org/visualization_earthquakes.html)... I managed to produce a map with my data plotted, [my successful image is here](https://github.com/HughP/Lexical-Database-Archiving-Stats/blob/master/2015-Hawaii/Formulas/Language_Plot_RandC.png): ![Lexical Database Archiving](https://github.com/HughP/Lexical-Database-Archiving-Stats/blob/master/2015-Hawaii/Formulas/Language_Plot_RandC.png)

I wanted to add some texture to my image so I thought I might try `map.bluemarble()` or `map.shadedrelief()` and in both cases I get a message saying that PIL was not installed, which is of course true, because I have brewed and am using Pillow 2.7.0. As you can see, I have gotten some image out of basemap, so I assume I am doing something correctly. Then [I consulted the documentation](http://matplotlib.org/basemap/users/installing.html) and saw that it said:
>**Optional libraries**

>PIL
>Python Imaging Library (download), only needed for `bluemarble()`, `etopo()`, `shadedrelief()` and `warpimage()` instance methods.

I hit two of four and the error message and thought I would ask.

@jenshnielsen With regards to the documentation. I have noticed that the version number for basemap available via pip is 1.0.7 while the [documentation says 1.0.8](http://matplotlib.org/basemap/index.html). I am not sure what the version here in github is, but it seemed that most repos([like sourcefoge](http://sourceforge.net/projects/matplotlib/files/matplotlib-toolkits/)) were reporting 1.0.7 as the latest version . Is this normal that documentation is a step ahead of the software package?

**Comment by WeatherGod** [comment]
It might be possible that Pillow isn't being found properly. Have you
successfully been able to use Pillow in the same python environment as
basemap?

**Comment by jenshnielsen** [comment]
@HughP I agree with @WeatherGod  It seems most likely that Pillow is not probably installed in your python environment. The only thing that basemap does is:

```python
from PIL import Image
```

This works with both PIL and pillow. Can you please try that in a python interpreter? 

I have no idea why the documentation is version 1.0.8. There is no such release. I just think that the documentation and the error message should referee to pillow rather than PIL.

**Comment by jenshnielsen** [comment]
If you look in the source code you can see that all these methods call `warpimage` which is the only method that uses PIL/PILLOW

**Comment by HughP** [comment]
About my environment: (OS X 10.9.5, Python 2.7.9. via homebrew, other homebrew brews via [`brew list`](https://gist.github.com/HughP/569b1a71bc5642121a0e) and other pip modules via [`pip list`](https://gist.github.com/HughP/ebc4f7592ccf1e53002d) ) I have my brewed python installed and have adjusted my path accordingly (I mean this is how I have been operating, I didn't just make a change on my system this for this thread).

`$ which python`
`/usr/local/bin/python`

using the `local/bin/python` PATH location is normal for homebrew setup of python and I manage this in my `.bash_profile`.
When I do `which pip` then I get `/usr/local/bin/pip` I take this to mean that `pip` and `python` are "on the same wavelength" and can communicate/are communicating.

When I run python in the command line and add `from PIL import Image` as @jenshnielsen suggests then I get `ImportError: No module named PIL`

if I do: `pip uninstall pillow` I get the following, followed by a `y/n?` of course I do a `no`.
`Uninstalling Pillow-2.7.0:
  /usr/local/lib/python2.7/site-packages/PIL
  /usr/local/lib/python2.7/site-packages/Pillow-2.7.0-py2.7.egg-info`

I uninstalled pillow via homebrew incase there were two versions. pip still says there is a version, even after I quit and restart the terminal, so I take this to mean that I am fine.

So to give this all another go, I went and ran [my modified version of the earthquake script as in this gist] (https://gist.github.com/HughP/a75e0c3caca56fc2d5a9)

Im' in the folder with my script and then in command line I start python and run 'import earthquake.py`
It chews on my data a bit, and then spits out an error.
If I comment out line 76 in the gist then the error does not happen and I get a map (sans blue marble effects).

The error looks as follows:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "earthquake.py", line 74, in <module>
    map.bluemarble()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py", line 3982, in bluemarble
    return self.warpimage(image='bluemarble',scale=scale,**kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py", line 4046, in warpimage
    raise ImportError('warpimage method requires PIL (http://www.pythonware.com/products/pil)')
ImportError: warpimage method requires PIL (http://www.pythonware.com/products/pil)'

**Comment by jenshnielsen** [comment]
@HughP  If you can't do `form PIL import Image` then pillow is not correctly installed. See the basic pillow tutorial: http://pillow.readthedocs.org/handbook/tutorial.html

**Comment by jenshnielsen** [comment]
I would recommend uninstalling pillow and make sure that all pil/pillow files are completely removed from `/usr/local/lib/python2.7/site-packages` and then reinstall it from scratch. 

Are you using https://github.com/homebrew/homebrew-python or pip to install python packages?
I don't have any experience with homebrew-python but both should work. But installing with one and uninstalling with the other is likely to give issues.

**Comment by HughP** [comment]
I uninstalled all copies of pillow and reinstalled one copy via pip (which is via  https://github.com/homebrew/homebrew-python) and now I have it working on both `bluemarble()` and `shadedrelief()` !!! thanks a bunch. Do you want me to open two issues about the documentation (version 1.0.8 and PIL/Pillow)?

**Comment by jenshnielsen** [comment]
Glad that it worked out. Yes I think it is fine to open an issue for the docs.
