### ISSUE TITLE
Basemap Dependencies update in the documentation.

### ISSUE THREAD

**Issue by HughP** [matplotlib/basemap#179]
[Basemap documentation](http://matplotlib.org/basemap/users/installing.html) currently says that PIL is required for some functions. However, PIL has largely been surpassed by Pillow. And in fact Pillow will work for basemap instead of PIL. So I recommend updating the documentation to reflect Pillow instead of PIL.

> **Optional libraries**
> 
> PIL
> Python Imaging Library (download), only needed for `bluemarble()`, `etopo()`, `shadedrelief()` and `warpimage()` instance methods.

**Comment by molinav** [comment]
I come from seven years later just to notify you that this part of the documentation has been updated. ;-)
