### ISSUE TITLE
Extra lines in drawcoastlines in ortho projection

### ISSUE THREAD

**Issue by jradavenport** [matplotlib/basemap#180]
These extra lines pop up at various places. I haven't (in 2 min of looking) found a pattern to their appearance yet

![frame0036](https://cloud.githubusercontent.com/assets/3179868/6320183/8c9cbfbc-ba8c-11e4-94b6-ab20a12e4472.jpeg)

**Comment by tacaswell** [comment]
Can you provide code to reproduce this?

**Comment by jradavenport** [comment]
https://gist.github.com/jradavenport/778260a1f0553575be99

Note of course this happens even w/o the underlying density map data

**Comment by WeatherGod** [comment]
Which version of matplotlib? This seems like a polygon closing issue.

**Comment by jradavenport** [comment]
version 1.4.0

Also have seen this kind of artifact [here](https://waterprogramming.wordpress.com/2013/11/02/python-makes-the-world-go-round/)

**Comment by jradavenport** [comment]
Have update to 1.4.3, and was on latest of basemap already.

Also can confirm issue occurs for high resolution
![figure_1](https://cloud.githubusercontent.com/assets/3179868/6338003/795087d4-bb60-11e4-9bbf-c27ef768cfce.png)

**Comment by WeatherGod** [comment]
I can't reproduce this using the latest matplotlib and basemap on master. I don't know what fixed this, but it seems to be fixed. Closing.
