### ISSUE TITLE
Basemap with Mplot3d Objects

### ISSUE THREAD

**Issue by essandess** [matplotlib/basemap#185]
I'm trying to use basemap globes as 3d objects along with other 3d plots with mplot3d, but basemap is throwing the following errors.

Example code:

```python
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.basemap import Basemap

bmap = Basemap(projection='ortho',lat_0=35,lon_0=68,resolution='l')

fig = plt.figure()
ax = Axes3D(fig)

ax.set_axis_off()
# ax.add_collection3d(bmap.bluemarble())
ax.add_collection3d(bmap.drawcoastlines(linewidth=0.25))
ax.add_collection3d(bmap.drawcountries(linewidth=0.35))

plt.show()
```

Error:

> AttributeError: 'Ellipse' object has no attribute 'do_3d_projection'

Uncommenting basemap's bluemarble() function throws the error

> AttributeError: 'AxesImage' object has no attribute 'get_datalim'

Is there any way to treat basemap plots as 3d objects? I have something [like this cartopy example](http://stackoverflow.com/questions/23785408/3d-cartopy-similar-to-matplotlib-basemap) in mind, except with 3d globe plotting.

**Comment by WeatherGod** [comment]
mplot3d does not support images, unfortunately. I don't know where the
Ellipse object is coming from, and it certainly shouldn't be getting to
that error, which is strange.

If you want 3d images, try glumpy.

I have been wanting to mash up mplot3d with basemap for years, but haven't
had the time to make it work.

**Comment by essandess** [comment]
Thanks. If you ever get the chance, here's a [Matlab example](http://www.mathworks.com/help/map/examples/plotting-a-3-d-dome-as-a-mesh-over-a-globe.html) of the general capability desired for basemap+mplot3d:

![mapex3ddome](http://www.mathworks.com/help/examples/map_product/mapex3ddome_05.png)

**Comment by WeatherGod** [comment]
closing as "wontfix"
