### ISSUE TITLE
corners (xmin, xmax, ymin, xmax) for a polar stereographic projection

### ISSUE THREAD

**Issue by gauteh** [matplotlib/basemap#189]
Hi,

I'm trying to set up a class for the IBCAO (polar stereographic coordinates, UPS) using Basemap. The center is at 90N,0E. The map is defined on a quadratic grid. When I set this and set the extent of the map (both width and height) I end up with xmin and ymin at 0 and xmax and ymax at twice their value. How can I get a situation where xmin = -xmax and ymin = -ymax?

https://github.com/gauteh/ibcao_py

**Comment by guziy** [comment]
Hi Gaute:

If you want to rotate your grid, you could use lon_0 argument in Basemap
constructor.

Cheers

2015-05-13 11:03 GMT-04:00 Gaute Hope <notifications@github.com>:

> Hi,
>
> I'm trying to set up a class for the IBCAO (polar stereographic
> coordinates, UPS) using Basemap. The center is at 90N,0E. The map is
> defined on a quadratic grid. When I set this and set the extent of the map
> (both width and height) I end up with xmin and ymin at 0 and xmax and ymax
> at twice their value. How can I get a situation where xmin = -xmax and ymin
> = -ymax?
>
> https://github.com/gauteh/ibcao_py
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matplotlib/basemap/issues/189>.
>



-- 
Sasha

**Comment by gauteh** [comment]
Hi, I dont want to rotate it, i want to center it at coordinates 0,0. Not
at xmax/2 and ymax/2 as it is now.

I can correctly specify the extent of the grid, but coordinates appear to
start at 0 and not -2490000 (for both x and y).

I already use lon0.

Gaute

Den onsdag 13. mai 2015 skrev Huziy Oleksandr (Sasha) <
notifications@github.com> følgende:

**Comment by guziy** [comment]
Have you tried to call set_xlim(minv, maxv) and set_ylim(vmin, vmax) on
your axes?

2015-05-13 15:38 GMT-04:00 Gaute Hope <notifications@github.com>:

> Hi, I dont want to rotate it, i want to center it at coordinates 0,0. Not
> at xmax/2 and ymax/2 as it is now.
>
> I can correctly specify the extent of the grid, but coordinates appear to
> start at 0 and not -2490000 (for both x and y).
>
> I already use lon0.
>
> Gaute
>
> Den onsdag 13. mai 2015 skrev Huziy Oleksandr (Sasha) <
> notifications@github.com> følgende:
>
> > Hi Gaute:
> >
> > If you want to rotate your grid, you could use lon_0 argument in Basemap
> > constructor.
> >
> > Cheers
> >
> > 2015-05-13 11:03 GMT-04:00 Gaute Hope <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
>
> >
> > > Hi,
> > >
> > > I'm trying to set up a class for the IBCAO (polar stereographic
> > > coordinates, UPS) using Basemap. The center is at 90N,0E. The map is
> > > defined on a quadratic grid. When I set this and set the extent of the
> > map
> > > (both width and height) I end up with xmin and ymin at 0 and xmax and
> > ymax
> > > at twice their value. How can I get a situation where xmin = -xmax and
> > ymin
> > > = -ymax?
> > >
> > > https://github.com/gauteh/ibcao_py
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/matplotlib/basemap/issues/189>.
> > >
> >
> >
> >
> > --
> > Sasha
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/matplotlib/basemap/issues/189#issuecomment-101749599
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matplotlib/basemap/issues/189#issuecomment-101789108>.
>



-- 
Sasha

**Comment by gauteh** [comment]
Plotting works fine, but converting between coordinates does not.

Den onsdag 13. mai 2015 skrev Huziy Oleksandr (Sasha) <
notifications@github.com> følgende:

**Comment by guziy** [comment]
If you want to define your own projection, probably it would be of interest
to look at the Cartopy project:
http://scitools.org.uk/cartopy/docs/latest/crs/projections.html

Otherwise, have you seen the answer to this question by Jeff Whitaker?:

http://matplotlib.1069221.n5.nabble.com/Basemap-with-origin-within-the-plot-td11308.html

2015-05-13 17:08 GMT-04:00 Gaute Hope <notifications@github.com>:

> Plotting works fine, but converting between coordinates does not.
>
> Den onsdag 13. mai 2015 skrev Huziy Oleksandr (Sasha) <
> notifications@github.com> følgende:
>
> > Have you tried to call set_xlim(minv, maxv) and set_ylim(vmin, vmax) on
> > your axes?
> >
> > 2015-05-13 15:38 GMT-04:00 Gaute Hope <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
> >
> > > Hi, I dont want to rotate it, i want to center it at coordinates 0,0.
> Not
> > > at xmax/2 and ymax/2 as it is now.
> > >
> > > I can correctly specify the extent of the grid, but coordinates appear
> to
> > > start at 0 and not -2490000 (for both x and y).
> > >
> > > I already use lon0.
> > >
> > > Gaute
> > >
> > > Den onsdag 13. mai 2015 skrev Huziy Oleksandr (Sasha) <
> > > notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> følgende:
> > >
> > > > Hi Gaute:
> > > >
> > > > If you want to rotate your grid, you could use lon_0 argument in
> > Basemap
> > > > constructor.
> > > >
> > > > Cheers
> > > >
> > > > 2015-05-13 11:03 GMT-04:00 Gaute Hope <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>:
>
> > >
> > > >
> > > > > Hi,
> > > > >
> > > > > I'm trying to set up a class for the IBCAO (polar stereographic
> > > > > coordinates, UPS) using Basemap. The center is at 90N,0E. The map
> is
> > > > > defined on a quadratic grid. When I set this and set the extent of
> > the
> > > > map
> > > > > (both width and height) I end up with xmin and ymin at 0 and xmax
> and
> > > > ymax
> > > > > at twice their value. How can I get a situation where xmin = -xmax
> > and
> > > > ymin
> > > > > = -ymax?
> > > > >
> > > > > https://github.com/gauteh/ibcao_py
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/matplotlib/basemap/issues/189>.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Sasha
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > https://github.com/matplotlib/basemap/issues/189#issuecomment-101749599
> > > >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/matplotlib/basemap/issues/189#issuecomment-101789108
> > >.
> > >
> >
> >
> >
> > --
> > Sasha
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/matplotlib/basemap/issues/189#issuecomment-101793503
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matplotlib/basemap/issues/189#issuecomment-101816940>.
>



-- 
Sasha

**Comment by gauteh** [comment]
I've solved this by using cartopy, might be possible in Basemap with the usage of false_easting and false_northing.
