### ISSUE TITLE
small bug in set_axes_limits

### ISSUE THREAD

**Issue by martalmeida** [matplotlib/basemap#193]
There is a small bug in set_axes_limits. The argument ax should be used in  the self.drawmapboundary calls, here:

        # if map boundary not yet drawn for elliptical maps, draw it with default values.
        if not self._mapboundarydrawn or self._mapboundarydrawn not in ax.patches:
            # elliptical map, draw boundary manually.
            if (self.projection in ['ortho','geos','nsper','aeqd'] and
                self._fulldisk) or self.round or self.projection in _pseudocyl:
                # first draw boundary, no fill
                limb1 = self.drawmapboundary(fill_color='none')  <----------------|
                # draw another filled patch, with no boundary.
                limb2 = self.drawmapboundary(linewidth=0)        <----------------|
                self._mapboundarydrawn = limb2

I found this cos I was getting a funny ellipse on my colorbar!

**Comment by WeatherGod** [comment]
Hmm, indeed. That seems like an easy enough fix. I'll put together a PR for
that.

**Comment by WeatherGod** [comment]
Just to note, PR #194 should fix this.
