### ISSUE TITLE
Issue saving as PDF

### ISSUE THREAD

**Issue by avipersin** [matplotlib/basemap#195]
There seems to be an issue when saving a basemap as a pdf when using shading='gouraud'.  

m.pcolormesh(x1, y1, data, shading='gouraud', cmap=plt.cm.jet)
m.drawmapboundary(fill_color='.3').  

Missing data renders properly as a PNG (greyish) but not as a PDF (where it turns black).

Here is what it looks like being saved as a PNG: http://imagebin.ca/v/29eyIEVNX2Cd
Here is what it looks like being saved as a PDF: http://imagebin.ca/v/29ez8ND80FDU

**Comment by WeatherGod** [comment]
I doubt this would be a basemap-specific issue. Which version of matplotlib
are you using?

**Comment by avipersin** [comment]
1.4.3

**Comment by tacaswell** [comment]
This might be fixed on master, there was a PR from @jkseppan that added alpha support to grayscale images.

**Comment by jkseppan** [comment]
Yes, probably fixed on master. The PR mentioned by @tacaswell is https://github.com/matplotlib/matplotlib/pull/4595.

**Comment by WeatherGod** [comment]
closing as it is likely fixed and there has been no follow-up.
