### ISSUE TITLE
Basemaps have dead areas

### ISSUE THREAD

**Issue by avipersin** [matplotlib/basemap#196]
When plotting data on a basemap using pcolormesh, there seems to be dead area on multiple projections.

Take a look at the white strip within the right border of Robinson Projection: http://ibin.co/2BEFvYYNQ9lZ

And the white strip within the right and top border of the Equidistant Cylindrical Projection: http://ibin.co/2BEG4bvCBaGH

And the weird business going on with the north polar projection: http://ibin.co/2BEGFqnB4Bez

Also, why is there no polar orthographic projection?  Is that something that can be added?

**Comment by WeatherGod** [comment]
Which version of basemap and which version of matplotlib? It would also be
useful to have a minimum code example to demonstrate the problem so that we
can investigate it better. At the moment, I have my suspicions, but I am
not sure without examples.

**Comment by avipersin** [comment]
matplotlib 1.4.3
basemap 1.0.7

Here is a working version: https://gist.github.com/avipersin/181eaadd0ecddd75567d

What are you thinking the issue is?

**Comment by avipersin** [comment]
This was actually an issue with the latitudes and longitudes I was generating.  I forgot that the np.arrange() function works on a half-open interval (for some odd reason).  

For that reason I was leaving out the last degree on each end, hence the white inner border.

Sorry about that.

**Comment by WeatherGod** [comment]
np.arange() mimics python's range() function, which is defined to be half-open ranges. Another useful function for building up coordinates is np.linspace(), which can be optionally half-open or inclusive.
