### ISSUE TITLE
shiftdata exception when using latlon=True for scatter

### ISSUE THREAD

**Issue by benranck** [matplotlib/basemap#197]
The exception;

```
m.scatter(x, y,50,marker='o',color='g',latlon=True, zorder=10)
  File Anaconda\lib\site-packages\mpl_toolkits\basemap\__init__.py", line 536, in with_transform
    x = self.shiftdata(x)
  File "Anaconda\lib\site-packages\mpl_toolkits\basemap\__init__.py", line 4777, in shiftdata
    if itemindex:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

There seems to be a mismatch when using latlon that shiftdata does not expect. This can be mitigated by getting the projection coordinates before applying the operation; example below.

```
from mpl_toolkits.basemap import Basemap
import numpy as np
import matplotlib.pyplot as plt

def valueError():
    m = Basemap(projection='robin',lon_0=115,resolution='c')
    m.drawcoastlines()
    m.fillcontinents(color='sienna',lake_color='aqua')
    m.drawmapboundary(fill_color='lightsteelblue')

    x = [-5.435, -6.660817, -119.2511944, 17.719833]
    y = [36.136, 4.746717, 39.4030278, -14.657583]
    m.scatter(x, y,50,marker='o',color='g',latlon=True, zorder=10)
    plt.show()

def works():
    m = Basemap(projection='robin',lon_0=115,resolution='c')
    m.drawcoastlines()
    m.fillcontinents(color='sienna',lake_color='aqua')
    m.drawmapboundary(fill_color='lightsteelblue')
    x = [-5.435, -6.660817, -119.2511944, 17.719833]
    y = [36.136, 4.746717, 39.4030278, -14.657583]

    x,y = m(x,y)
    m.scatter(x, y,50,marker='o',color='g',latlon=False, zorder=10)
    plt.show()

def main():
    works()
    valueError()

if __name__ == '__main__':
    main()
```

**Comment by samskillman** [comment]
I just encountered the same issue.

**Comment by guziy** [comment]
Actually sorting data by longitude like this seems to work, not, sure if this is a good fix... But maybe we could just sort longitudes in scatter if latlon is True??:

```python
from mpl_toolkits.basemap import Basemap
import numpy as np
import matplotlib.pyplot as plt


def valueError():
    m = Basemap(projection='robin',lon_0=115,resolution='c')
    m.drawcoastlines()
    m.fillcontinents(color='sienna',lake_color='aqua')
    m.drawmapboundary(fill_color='lightsteelblue')

    x = [-5.435, -6.660817, -119.2511944, 17.719833]
    y = [36.136, 4.746717, 39.4030278, -14.657583]
    
    
    x, y = list(zip(*sorted(zip(x, y), key=lambda it: it[0])))
    m.scatter(x, y,50,marker='o',color='g',latlon=True, zorder=10)
    plt.show()
```

Here is the working notebook: https://github.com/guziy/PyNotebooks/blob/master/basemap_scatter.ipynb

Cheers

**Comment by samskillman** [comment]
I pre-sorting works for scatter, but not pcolormesh. Seems like the issue comes from itemindex being an array rather than a value:

```
4773         # 2-d data.
4774         if lonsin.ndim == 2:
4775             nlats = lonsin.shape[0]
4776             nlons = lonsin.shape[1]
4777             lonsin1 = lonsin[0,:]
4778             lonsin1 = np.where(lonsin1 > lon_0+180, lonsin1-360 ,lonsin1)
4779             lonsin1 = np.where(lonsin1 < lon_0-180, lonsin1+360 ,lonsin1)
4780             londiff = np.abs(lonsin1[0:-1]-lonsin1[1:])
4781             londiff_sort = np.sort(londiff)
4782             thresh = 360.-londiff_sort[-2]
4783             itemindex = nlons-np.where(londiff>=thresh)[0]
4784             # if no shift necessary, itemindex will be
4785             # empty, so don't do anything
4786             if itemindex:
4787                 # check to see if cyclic (wraparound) point included
4788                 # if so, remove it.
4789                 if np.abs(lonsin1[0]-lonsin1[-1]) < 1.e-4:
4790                     hascyclic = True
4791                     lonsin_save = lonsin.copy()
4792                     lonsin = lonsin[:,1:]
4793                     if datain is not None:
4794                        datain_save = datain.copy()
4795                        datain = datain[:,1:]
4796                 else:
4797                     hascyclic = False

```

**Comment by guziy** [comment]
@samskillman Could you please post a minimal example of your coordinates and a failing code with pcolormesh?

**Comment by guziy** [comment]
@samskillman Please make sure that your data has the following order of dimensions: Z(lat, lon), LON(lat, lon), LAT(lat, lon)

apparently shiftdata expects it to be like that...

        Shift longitudes (and optionally data) so that they match map projection region.
        Only valid for cylindrical/pseudo-cylindrical global projections and data
        on regular lat/lon grids. longitudes and data can be 1-d or 2-d, if 2-d
        it is assumed longitudes are 2nd (rightmost) dimension.

**Comment by cpaulik** [comment]
I've got the same problem and it is because you can not test for array existence in the if statement.

See this minimal example:

```python
In [1]: import numpy as np

In [2]: a = np.arange(10)

In [3]: itemindex = len(a) - np.where(a > 5)[0]

In [4]: itemindex
Out[4]: array([4, 3, 2, 1])

In [5]: if itemindex:
   ...:     print "test"
   ...:     
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-758a9d9e7b06> in <module>()
----> 1 if itemindex:
      2     print "test"
      3 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by guziy** [comment]
shiftdata seems to be able to only handle 1 break....

Are you trying to scatter or pcolormesh? Is projecting first and plotting without latlon=True works?

Cheers

**Comment by bencpeters** [comment]
I'm running into this issue as well. I tried modifying line 4734 to `if itemindex.any()` (basically checking if the array is empty or not), but then you run into an error further on with the call to `np.roll` - `itemindex - 1` isn't a scalar, it's an array...

**Comment by kiwi937** [comment]
Also experiencing this issue. And I discovered that there's been a pull request ([#224](https://github.com/matplotlib/basemap/pull/224)) to fix this bug open for a year now; any reason it hasn't been merged in yet?

**Comment by WeatherGod** [comment]
Well, that PR doesn't totally fix the problem, and there was an open question about whether the fix was correct or not. Does it make things work for you?

**Comment by kiwi937** [comment]
@WeatherGod actually it appears to totally randomize the longitudes. For now I've just blocked off the buggy code by changing `if itemindex` to `if False` and it's behaving as expected. Not sure what the point of the entire block is either as only one of two datasets I'm working with trigger it (i.e. itemindex is not empty) and both are on a -180° to 180° longitude grid.

**Comment by kiwi937** [comment]
@WeatherGod just ran into this bug again. I would love to try and fix this if anyone could explain what the `if itemindex:` block is supposed to achieve

**Comment by guziy** [comment]
I am somehow slow with getting this fixed, sorry about that ... The shiftdata function is called from many places and this complicates things for me)) Would be great to get rid of the problem before 2017..

**Comment by kiwi937** [comment]
@guziy what is the purpose of shiftdata?

**Comment by WeatherGod** [comment]
Shiftdata helps to deal with the 0/360 or -180/180 wrap-around problem in
plotting.

**Comment by guziy** [comment]
If I understand correctly it is to make your field continuous and keep the coordinates within the ranges of your projection... But this should always be checked against the doc https://github.com/matplotlib/basemap/blob/master/lib/mpl_toolkits/basemap/__init__.py#L4719

Cheers

**Comment by guziy** [comment]
@kiwi937 could you please provide an example of your failing case? 

Cheers and Happy New Year))

**Comment by WeatherGod** [comment]
This specific issue should be fixed for scatter(). Doing something similar for plot() might still fail, though.
