### ISSUE TITLE
Color scale in Basemap plots

### ISSUE THREAD

**Issue by abhigenie92** [matplotlib/basemap#205]
map = Basemap(resolution ='c')
    map.drawcoastlines()
    map.drawcountries()
    map.drawmeridians(np.arange(0, 360, 30))
    map.drawparallels(np.arange(-90, 90, 30))
    map.bluemarble()
    lat_list=worksheet.col_values(16)
    long_list=worksheet.col_values(17)
    lat_list.remove('lat')
    long_list.remove('lon')
    for index in range(0,len(lat_list)):
        x, y = map(long_list[index],lat_list[index])
        map.plot(x, y, 'bo', markersize=5)
The above plots points on a map. I have a list of size same as lat_list and long_list. I want to make the points on the map colored according to that also show a color scale on the map with corresponding label.
Link:http://stackoverflow.com/questions/32514143/color-scale-in-basemap-plots

**Comment by guziy** [comment]
Hi

Do you want something like this?:

https://github.com/guziy/PyNotebooks/blob/master/simple_scatter_basemap.ipynb

Read scatter documentation it has similar options as the one in matplotlib.

Cheers

**Comment by abhigenie92** [comment]
Thanks exactly what I wanted. Cna you also tell how to change the markersize.
I tried this :
    s=map.scatter(x,y,'o', markersize=5,c=input_clean,s=60)
but it gave me the error:
  ret =  ax.scatter(*args, **kwargs)
TypeError: scatter() got multiple values for keyword argument 's'

**Comment by guziy** [comment]
Here is an example with matplotlib axes:
http://matplotlib.org/mpl_examples/shapes_and_collections/scatter_demo.py

But for most cases keyword arguments work the same way in basemap.

I think markersize should be removed...

Cheers

2015-09-12 22:08 GMT-04:00 abhigenie92 <notifications@github.com>:

> Thanks exactly what I wanted. Cna you also tell how to change the
> markersize.
> I tried this :
> s=map.scatter(x,y,'o', markersize=5,c=input_clean,s=60)
> but it gave me the error:
> ret = ax.scatter(*args, **kwargs)
> TypeError: scatter() got multiple values for keyword argument 's'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matplotlib/basemap/issues/205#issuecomment-139839612>.
>



-- 
Sasha

**Comment by guziy** [comment]
I think this should be closed.

**Comment by QuLogic** [comment]
Agreed; this is not a bug or feature request.
