### ISSUE TITLE
shadedrelief() fails because of changes in numpy.concatenate

### ISSUE THREAD

**Issue by r5r3** [matplotlib/basemap#211]
In `basemap/__init__.py` in Line 4151 the array `self._bm_lons` is created with one dimension. In line 4169 it is concatenated to itself, but not with dimension 0 but with dimension 1.

Since numpy version 1.10 this is an error.

**Comment by WeatherGod** [comment]
Thank you for the bug report. If you'd like, could you make a PR with this
fix and I'll merge it in?

**Comment by WeatherGod** [comment]
Uhm, I think you made a merge request against your own fork rather than against this one?
