### ISSUE TITLE
Recommend Pillow over PIL?

### ISSUE THREAD

**Issue by micahcochran** [matplotlib/basemap#239]
PIL's development seems to have been discontinued in 2011 ([Wikipedia](https://en.wikipedia.org/wiki/Python_Imaging_Library)).  [Pillow](http://python-pillow.github.io/) is an [active fork](https://github.com/python-pillow/Pillow/graphs/contributors) PIL.  Pillow supports Python 3.x and compatibility with PyPy.

PIL is an optional dependency to use `warpimage()`.  (There are a few functions that call it to use an image provided in the data, such as bluemarble, shadedrelief, and etopo.)

My machine already had Pillow installed, so it already seems to just work.   

Are there any issues with changing the recommendation from the package PIL to Pillow?

The longer term solution might be to replace or extend `warpimage()` with rasterio or another package.  @WeatherGod has suggested rasterio.

**Comment by WeatherGod** [comment]
Yes, the recommendation should be changed to Pillow. When Pillow is
installed, it installs itself as PIL, so old code continues to work.

**Comment by micahcochran** [comment]
PR #241 which updated the README included this.  This has been completed.
