### ISSUE TITLE
Python 3.5 (windows)

### ISSUE THREAD

**Issue by dkleehammer** [matplotlib/basemap#249]
Anaconda now has a python 3.5 version in public (non-rc) is basemap going to be update soon to work on windows with 3.5?

**Comment by micahcochran** [comment]
I don't think this project is supporting anaconda binaries.

**Comment by WeatherGod** [comment]
It is up to continuum analytics to create the binaries. The individual
projects do not package the binaries (with exception to those who do so
through their own channels).

**Comment by dkleehammer** [comment]
Conda can install from pip, but basemap is only for 2.7 and 3.3 on Windows and up to 3.5 on Linux distros.  Even the downloads area in the documentation say this.  So if a Windows 3.5 version was at least installable through pip or even the installer binaries for Windows could be made, I'd be able to use Python 3.5 for everything.

I'll work with the conda group to get a version in their package manager, although I would guess they wouldn't be able to until setup.py is ready to run on Python 3.5.  Conda finds the current version and reads the distutils to check for descrepancies before it attempts to install.

**Comment by jswhit** [comment]
Christoph Gohlke has 3.5 binaries for windows:

http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by guziy** [comment]
Hi Daniel:

Can conda install from github? If yes then you could point it to the latest
master, there is no upper bound on python version there... And I also
successfully installed it for python 3.5 and ran examples (although on
Linux), so it should work...


Cheers

2015-12-30 22:11 GMT-05:00 Jeff Whitaker <notifications@github.com>:

> Christoph Gohlke has 3.5 binaries for windows:
>
> http://www.lfd.uci.edu/~gohlke/pythonlibs/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matplotlib/basemap/issues/249#issuecomment-168114356>.
>



-- 
Sasha

**Comment by micahcochran** [comment]
@guziy Installing from github kinda defeats the point of conda.  You have to compile `_geoslib.c` even if you have libgeos installed.

**Comment by guziy** [comment]
2015-12-31 10:18 GMT-05:00 Micah Cochran <notifications@github.com>:

> @guziy <https://github.com/guziy> Installing from github kinda defeats
> the point of conda. You have to compile _geoslib.c even if you have
> libgeos installed.
>

It would be nice if conda could do it, pip (on Linux) does it for me....
But I have no experience with windows and very little with conda...

Cheers

-- 
Sasha

**Comment by dkleehammer** [comment]
@guziy I was able to use the wheel that @jswhit suggested and using conda's pip version, I got it to install.

As for getting basemap into windows for 3.5 and to help others out based upon the documentation website, can someone get an installer for 3.5 for windows out to here:
http://sourceforge.net/projects/matplotlib/files/matplotlib-toolkits/basemap-1.0.7/

Documentation: http://matplotlib.org/basemap/users/download.html

Since I was able to get it to install, this comment is closed.  Thanks for the help!  Thanks @jswhit

**Comment by WeatherGod** [comment]
my hope is that the next release (~a month or 2 from now) will utilize
appveyor, and as such, we will be able to release binaries for windows.

**Comment by dkleehammer** [comment]
Ok thanks @WeatherGod

**Comment by fbender** [comment]
> my hope is that the next release (~a month or 2 from now) will utilize appveyor, and as such, we will be able to release binaries for windows.

@WeatherGod did this ever happen? I can only find the binaries on SF for 3.3. Also, the wheels from Christoph Gohlke are at v1.0.8 though git only has an v1.0.7 tag so I'm a bit wary to use them ... is that version from master? Is it safe to use?

**Comment by WeatherGod** [comment]
No, I still haven't done a release (haven't figured everything out yet).
Christoph's v1.0.8 is basically what was on master when he made them
because v1.0.7 was so old. They should be good to use.
