### ISSUE TITLE
Basemap very slow instantiating high-res GSHHS/GSHHG coastlines

### ISSUE THREAD

**Issue by dnowacki-usgs** [matplotlib/basemap#252]
Instantiating Basemap using `resolution="h"` or `resolution="f"` can require considerable time (tens of seconds to minutes). My understanding is that Basemap must load the entire GSHHS database even if one is interested in only a small region ([here's a relevant SO question](http://stackoverflow.com/questions/24635725/reduce-the-size-of-matplotlib-basemap)).

I'm coming from Matlab, where the [M_Map](http://www.eos.ubc.ca/~rich/map.html) package deals with this issue by generating "user coast" files. M_Map has a function (in `mu_coast.m`) wherein one can read the full GSHHS database once, extract the high-res data just for the area of interest, and save it to a (much faster-loading) file that can be read in the future. From what I can tell, there is a fair amount of logic required to do this extraction, but it is possible. Is there any potential for this type of functionality to be built into Basemap in the future? Alternatively, are there currently any workarounds that maintain the built-in Basemap functions that use GSHHS (e.g., `fillcontinents`, `drawcoastlines`)? Is reading a custom shapefile the best option here?

Thanks!

**Comment by efiring** [comment]
On 2016/01/11 5:41 AM, dnowacki-usgs wrote:
> Instantiating Basemap using |resolution="h"| or |resolution="f"| can
> require considerable time (tens of seconds to minutes). My understanding
> is that Basemap must load the entire GSHHS database at high or full
> resolution even if one is interested in only a small region. This is
> generally the case, I think: no one's likely to make a continent-scale
> map at full resolution, but Basemap has to read in the full database
> anyway (here's a relevant SO question
> <http://stackoverflow.com/questions/24635725/reduce-the-size-of-matplotlib-basemap>).
>
> I'm coming from Matlab, where the M_Map
> <http://www.eos.ubc.ca/%7Erich/map.html> package deals with this issue
> by generating "user coast" files. M_Map has a function (in |mu_coast.m|)
> wherein one can read the full GSHHS database once, extract the high-res
> data just for the area of interest, and save it to a (much
> faster-loading) file that can be read in the future. From what I can
> tell, there is a fair amount of logic required to do this extraction,
> but it is possible. Is there any potential for this type of
> functionality to be built into Basemap in the future? Alternatively, are
> there currently any workarounds that maintain the built-in Basemap
> functions that use GSHHS (e.g., |fillcontinents|, |drawcoastlines|)? Is
> reading a custom shapefile the best option here?

I have a cache option in my basemap wrapper:
http://currents.soest.hawaii.edu/hgstage/pycurrents/file/70015144b883/plot/maptools.py

Eric

**Comment by micahcochran** [comment]
Creating a data subset is definitely an approach, and you'd probably see a bit of a performance boost.  There are other approaches that could likely improve performance.  I'd like to see profiling for the performance bottleneck.

**Comment by WeatherGod** [comment]
IIRC, I raised an issue similar to this with Jeff awhile back. Part of the
problem is that if one does subsetting, then it gets very tricky to deal
with panning and zooming. At that time, I was a complete novice to
matplotlib and didn't know anything about the interactive part of
matplotlib. Now, I could do the interactive part, so it wouldn't be
impossible to implement, but I would first need the subsetting feature to
be available. Once that is present, I could implement the needed callback
hooks that could update the relevant data needed for updating the display.

**Comment by jswhit** [comment]
You can pickle a basemap instance and reuse it in another script.  If you're using the same projection region, this avoids the overhead of creating the instance.

**Comment by dnowacki-usgs** [comment]
Thanks for the helpful replies, everyone. It hadn't occurred to me that caching/pickling would be so easy to implement, and fast. I'm good with that approach (I don't need interactivity). If there is interest I'd be happy to contribute text to the docs to this effect.

@micahcochran regarding performance, the most time-intensive parts of creating a new basemap instance seem to be the geoslib `is_valid`, `union`, and `intersection` methods.
