### ISSUE TITLE
new image comparison unit tests

### ISSUE THREAD

**Issue by micahcochran** [matplotlib/basemap#253]
Here are some ideas that I have about adding image comparison unit test.  I want to get some input about this before I do too much coding on this.
- Improve the examples/ to take CLI arguments that will plot to files when given `--plot-file`, and not display the plot to the screen when given `--no-display`.  (`--no-display` is so that Travis will not get hung by any required interactivity.)
- Create new image comparison unittests that call the examples/. 
- Since the examples/ are not installed, the unit tests should not be installed?

Or should the unit tests be installed?  If they are installed it will add a few megabytes of test PNG images that will only be used when test() is called.

I am leaning towards not installed image comparison unit tests.  Any thoughts?  Is there something that I may not be considering?

I hope that this might lead to enough unittesting that could allow us to start the process of rewriting portions of the basemap code.

**Comment by micahcochran** [comment]
I've started the above unit tests on my [img-tests fork](https://github.com/micahcochran/basemap/tree/img-tests).  This is not installed by setup.py.

[The results seem pretty good](https://travis-ci.org/micahcochran/basemap/builds/102865586).  The test with matplotlib 1.4.3 is failing due to a high RMS between the images.  (I've not seen how different the image looks.) "nightly" is failing because contourf has another instance of a numpy array being indexed by a casted floating point value due to division.

[Before I increased the compare_image tolerance to a RMS of 10](https://travis-ci.org/micahcochran/basemap/builds/102861270) all the test failed because the tolerance was a RMS of 0.001  RMS tolerance of 10 was determined by looking at what is typical for unit testing in matplotlib and geopandas.

**Comment by micahcochran** [comment]
I installed matplotlib 1.4.3.  At a glance, I can't really tell the difference between this and other generated versions.  

Some options.
1. I might be comfortable upping the RMS of these two tests a little.  
2. Another is just just allow the RMS to be higher for this particular version for these tests.
3. A final option might be to drop support for this version and focus support 1.5.x for 2.0.x

Let me know.  Thanks!

**plotmap.png**
![plotmap](https://cloud.githubusercontent.com/assets/7433104/12566040/362f3b50-c37d-11e5-9163-955f078d4753.png)
![plotmap-failed-diff](https://cloud.githubusercontent.com/assets/7433104/12566041/362f433e-c37d-11e5-822a-e38d3cde80c8.png)

**simpletest.png**
![simpletest](https://cloud.githubusercontent.com/assets/7433104/12566039/362d15b4-c37d-11e5-91a7-83636fefcf1f.png)
![simpletest-failed-diff](https://cloud.githubusercontent.com/assets/7433104/12566038/3622ecce-c37d-11e5-95d7-879e2f546bb9.png)

**Comment by WeatherGod** [comment]
There are some lessons that can be learned from recent work in matplotlib:
https://github.com/matplotlib/matplotlib/pull/5307/

Not all of it can be taken advantage of right now, but some of it can be.
Another thing to consider is to ignore text for now in most of the tests,
focusing instead on correctness of the projections.
