### ISSUE TITLE
pyproj fails with Fortran-order input

### ISSUE THREAD

**Issue by efiring** [matplotlib/basemap#266]
Lon, lat input arrays in Fortran order (such as one might read from a Matlab mat file) cause a RuntimeError:

```python
import numpy as np
from mpl_toolkits.basemap import Basemap

order = 'F'   #  works if this is 'C'
shape = (2, 4)
lon = np.ones(shape, dtype=float, order=order)
lat = 20 + np.ones(shape, dtype=float, order=order)

m = Basemap(width=10000, height=10000, lon_0=0,
            lat_0=10, lat_1=20, lat_2=30,
            projection='lcc')
m(lon, lat)
```
I think a reasonable place to fix this will be `proj.Proj.__call__()` via `np.ascontiguousarray()` calls.

**Comment by guziy** [comment]
Hi @efiring : could you please check if this is related #209.

Cheers

**Comment by efiring** [comment]
Yes, this looks like a duplicate of #209, in which case the problem becomes one of getting an updated Basemap into widespread use, starting with Anaconda.

**Comment by WeatherGod** [comment]
Yes, I was waiting for a few other PRs to finalize, but perhaps I shouldn't
hold off much longer.

**Comment by micahcochran** [comment]
@WeatherGod Here's my suggestion.  Make an issue of the next release with tasklist of what should be done for the next release, and give it an anticipated date for the next release.  

This will give us contributors time to fix issues.
