### ISSUE TITLE
Raspberry pi + basemap

### ISSUE THREAD

**Issue by whyvas** [matplotlib/basemap#274]
I am trying to get basemap to run on a raspberry pi connected to a 800x480 touchscreen. I've tried two examples and neither work correctly, here's one tutorial I tried: https://www.sparkfun.com/tutorials/403 everything is installed and it runs but I only get a blank window with Figure 1 as the title and the 7 icons at the bottom left corner but no map displays. Any ideas on what the issue could be?

**Comment by whyvas** [comment]
Python 2.7.3, Linux 4.1.13-v7+(raspbian)

**Comment by WeatherGod** [comment]
Well, first things first, does regular matplotlib work properly?

**Comment by whyvas** [comment]
Sorry for the delay, it doesn't. 
I tried with:

import matplotlib.pyplot as plt
plt.plot([1,2,3,4])
plt.ylabel('some numbers')
plt.show()

I get the same result. There are 3 warnings if that sheds any light, 2 about CSS fallback and 1 about accessibility bus. 

I found on a chinese forum that someone installed gnome and it worked, is gnome a requirement? It's a 1.5gb install on the pi and would likely bring it to its knees.

**Comment by WeatherGod** [comment]
You need a gui for interactivity (i.e., plt.show()). If you just want to
make png's, then you don't need any gui's, it can act like a headless
server. Python, by default, will build with the Tk gui, and matplotlib will
utilize it by default (assuming the tk/tcl headers were available at
build-time for matplotlib). Since you are saying that you have a window
with buttons and such, I'd say you got that part working fine.

Warnings about CSS fallback? That's weird, since matplotlib doesn't use CSS
(unless possibly the webagg/nbagg backends). What are the warnings?

**Comment by whyvas** [comment]
I've figured it out, for anyone who might find this thread, it was the backend, it was using GTK3agg by default which doesn't seem to work on a raspberry pi. tkagg does. I had to remove matplotlib from apt and pip, install the tk and tk-dev packages then reinstall using the github version. So:

apt-get remove matplotlib
pip uninstall matplotlib
apt-get install tk tk-dev
git clone https://github.com/matplotlib/matplotlib.git
cd matplotlib
python setup.py install

and finally I had to make sure that every python file contained 

import matplotlib
matplotlib.use("TkAgg")

at the very top.

**Comment by WeatherGod** [comment]
That's good to know. I should point out that those two lines aren't
actually needed. In ~/.config/matplotlib/matplotlibrc (or something like
it), there is an entry for the default backend to use. Just set that to
TkAgg, and that backend will be used without those lines being needed in
the code.

Glad you got it working!
Cheers!
Ben Root

**Comment by whyvas** [comment]
Hmm, well now you have me wondering if that would of solved my issue all along... hahah, sigh.

**Comment by WeatherGod** [comment]
Maybe, maybe not. The tkagg backend is only available if the tk-dev files
are available at the buildtime for matplotlib. There is a tiny C shim that
is needed to make tkagg work with matplotlib. So, you probably still needed
to have those packages installed anyway.
