### ISSUE TITLE
Downloads from Sourceforge

### ISSUE THREAD

**Issue by beardedprojamz** [matplotlib/basemap#277]
Hi there,

I went to install basemap, and reviewed all the install steps, seeing that I needed to download the library manually, I preceded to Sourceforge (:confounded:) to download the release. It went like this:

<img width="1021" alt="screen shot 2016-03-11 at 12 40 39 pm" src="https://cloud.githubusercontent.com/assets/877908/13712477/76c8f87e-e789-11e5-839f-a0b0f60cb6cc.png">
<img width="391" alt="screen shot 2016-03-11 at 12 43 42 pm" src="https://cloud.githubusercontent.com/assets/877908/13712478/76ca6664-e789-11e5-98b2-b8f24198a3cd.png">

While the file was *still* downloading from SF, I looked for github releases due to the prompting of a coworker, and I found you all did have some up. I downloaded the same release from GH before the SF one ever finished.

<img width="433" alt="screen shot 2016-03-11 at 12 47 28 pm" src="https://cloud.githubusercontent.com/assets/877908/13712496/9b0bd210-e789-11e5-83ab-ee645bd22e42.png">

Is this project still using Sourceforge for anything, or is it just legacy stuff? If it's legacy, would you consider a Pull Request to update the README and docs to point to the github releases page instead of sourceforge? Thanks!

**Comment by WeatherGod** [comment]
The sourceforge stuff was where the pypi page pointed to. The next release
(whenever I manage to free up time to do it) will be hosted directly from
pypi's servers instead as well as posting the release tarballs on github.

Yes, please do submit a PR to update the README, especially since pip now
no longer installs from sourceforge automatically.

**Comment by beardedprojamz** [comment]
I've submitted a super small PR at #278.

**Comment by WeatherGod** [comment]
closed via #278
