### ISSUE TITLE
ImportError: libgeos_c.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mharradon** [matplotlib/basemap#302]
In case anybody runs into this in the future, I had to add /usr/local/lib/ to LD_LIBRARY_PATH on my machine to properly import the library after installation:

`export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH`

**Comment by jdkloe** [comment]
[also for futurte reference]
in general I would consider adding a LD_LIBRARY_PATH definition in your bashrc (I assume that's where you put it) a bad idea. It can have unexpected side effects later and cause very hard to track segfaults/crashes in the future when your system gets updated/upgraded, after which other applications that happen to use the same library try to load an incompatible library version. If you really need to use a custom library version in your application, I would recommend to wrap your application in a small shell (or python) script and put the LD_LIBRARY_PATH definition in the script just before you call your application. That way you can be sure there will be no side effects for other applications.

**Comment by DarnelleF** [comment]
for those building from source. 

> sudo ldconfig
