### ISSUE TITLE
Where is v1.0.8 tag?

### ISSUE THREAD

**Issue by davidedelvento** [matplotlib/basemap#303]
If I have to believe to: http://www.lfd.uci.edu/~gohlke/pythonlibs/#basemap and http://matplotlib.org/basemap/users/download.html (see the top left link), there should exist a v1.0.8 release of basemap.

However there's no trace of it in either https://sourceforge.net/projects/matplotlib/files/matplotlib-toolkits/ or https://github.com/matplotlib/basemap/releases

**Comment by QuLogic** [comment]
See #267.
