### ISSUE TITLE
Basemap instance not returning correction projection values?

### ISSUE THREAD

**Issue by ParseThis** [matplotlib/basemap#307]
Grand picture: I am creating a choropleth  and would like to annotate the state polygons with their respective abbreviations (New York becomes NY). The way I see to do this would be to use my basemap instance to project the centroids (lat, lon) and then annotate using ``` ax.annotate ```. However  it seems basemap is returning values that is causing ax.annotate to seg fault. To reproduce try (for Wyoming):

```
m =Basemap(llcrnrlon=-119,llcrnrlat=22,urcrnrlon=-64,urcrnrlat=49,projection='lcc',lat_1=33,lat_2=45,lon_0=-95)

#wyoming's lat, long
wy_lat, wy_lon = 42.7475,-107.2085

m(wy_lat, wy_lon) ```

returns (1e+30, 1e+30)
```

Is that what I should expecting? Or any on the annotation?
Thanks so much!

**Comment by guziy** [comment]
Try using  x,y = m(wy_lon, wy_lat) # the order is important.
Cheers

Le dimanche 3 juillet 2016, Orson Adams <notifications@github.com> a écrit :

> Grand picture: I am creating a choropleth and would like to annotate the
> state polygons with their respective abbreviations (New York becomes NY).
> The way I see to do this would be to use my basemap instance to project the
> centroids (lat, lon) and then annotate using ax.annotate. However it
> seems basemap is returning values that is causing ax.annotate to seg fault.
> To reproduce try (for Wyoming):
>
> m =Basemap(llcrnrlon=-119,llcrnrlat=22,urcrnrlon=-64,urcrnrlat=49,projection='lcc',lat_1=33,lat_2=45,lon_0=-95)
>
> #wyoming's lat, long
> wy_lat, wy_lon = 42.7475,-107.2085
>
> m(wy_lat, wy_lon) ```
>
> returns (1e+30, 1e+30)
>
> Is that what I should expecting? Or any on the annotation?
> Thanks so much!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/matplotlib/basemap/issues/307>, or mute the thread
> <https://github.com/notifications/unsubscribe/AA2_TTlNQ9p8aGLPvZCuHuK3hV0FqS-rks5qR-mKgaJpZM4JD57c>
> .
>


-- 
Sasha

**Comment by ParseThis** [comment]
@guziy thanks!! that worked.
