### ISSUE TITLE
AttributeError: 'AxesSubplot' object has no attribute 'get_facecolor'

### ISSUE THREAD

**Issue by fmv1992** [matplotlib/basemap#315]
Hi,

I have a code which runs fine on my lubuntu machine but on my cygwin throws me the following error:
```
Traceback (most recent call last):
  File "bonus_assignment_01_fiji_earthquakes.py", line 69, in <module>
    themap.fillcontinents(color='gainsboro')
  File "/usr/lib/python3.4/site-packages/mpl_toolkits/basemap/__init__.py", line 1753, in fillcontinents
    axisbgc = ax.get_facecolor()
AttributeError: 'AxesSubplot' object has no attribute 'get_facecolor'
```
I'm attaching the code.
[bonus_assignment_01_fiji_earthquakes.zip](https://github.com/matplotlib/basemap/files/432197/bonus_assignment_01_fiji_earthquakes.zip)

I have installed basemap in both machines from the same source/version which is this website. Any idea why this happens?

**Comment by fmv1992** [comment]
Removing the if/else statement and using the 'else' content only solves the problem:
(lines 1752-1755)

> #        if _matplotlib_version >= '1.5':
> #            axisbgc = ax.get_facecolor()
> #        else:
> #            axisbgc = ax.get_axis_bgcolor()
>         axisbgc = ax.get_axis_bgcolor()

I am not sure if this affect other people so I'll wait until I can submit a pull request.

**Comment by jenshnielsen** [comment]
Which version of Basemap are you using?

It the latest master this check has been changed to check for matplotlib 2.0 https://github.com/matplotlib/basemap/blob/master/lib/mpl_toolkits/basemap/__init__.py#L1653
Matplotlib 2.0 beta does have the `ax.get_facecolor`

In the latest official release (1.0.7) the if statement does not exist. https://github.com/matplotlib/basemap/blob/1d7664cdd60951069b972071d1b1b71feabb8b95/lib/mpl_toolkits/basemap/__init__.py#L1622

**Comment by fmv1992** [comment]
I did ` git clone https://github.com/matplotlib/basemap` and `git pull` gives me `Already up-to-date.`.

Is there a different way to get this repo?

**Comment by jenshnielsen** [comment]
What does `git log` show as the latest commit? Git blame https://github.com/matplotlib/basemap/blame/master/lib/mpl_toolkits/basemap/__init__.py shows that the code has only had the check for `1.5` a few days in May this year and fixed after that.

**Comment by srinify** [comment]
Unfortunately, the issue exists in the fillcontinents() method, even though it was fixed in drawmapboundary() - https://github.com/matplotlib/basemap/blob/master/lib/mpl_toolkits/basemap/__init__.py#L1753
