### ISSUE TITLE
AttributeError: 'AxesSubplot' object has no attribute 'get_facecolor' still exists, only partially fixed.

### ISSUE THREAD

**Issue by srinify** [matplotlib/basemap#316]
While checking for get_facecolor() method was updated from 1.5 to 2.0 in the drawmapboundary() method - https://github.com/matplotlib/basemap/blob/master/lib/mpl_toolkits/basemap/__init__.py#L1654 :

```
if fill_color is None:
            if _matplotlib_version >= '2.0':
                fill_color = ax.get_facecolor()
```

the issue still exists in the fillcontinents() method:

https://github.com/matplotlib/basemap/blob/master/lib/mpl_toolkits/basemap/__init__.py#L1753 : 

```
if _matplotlib_version >= '1.5':
            axisbgc = ax.get_facecolor()
```

and causes it to to throw the following error:

```
AttributeError: 'AxesSubplot' object has no attribute 'get_facecolor'
```

**Comment by WeatherGod** [comment]
Good catch! I don't know how I missed that.
