### ISSUE TITLE
Release wheels for all platforms

### ISSUE THREAD

**Issue by ariddell** [matplotlib/basemap#319]
It would be great to have binary wheels for all platforms.

With https://github.com/stan-dev/pystan we used the following strategy:
- Windows wheels using appveyor following https://github.com/ogrisel/python-appveyor-demo wheels 
- manylinux1 and macOS wheels using travis-ci following https://github.com/MacPython/matplotlib-wheels

It all works. The only downside is that it's an enormous pain to sign and upload ~15 large artifacts to pypi.

EDIT: fix link

**Comment by matthew-brett** [comment]
I use wheel-uploader for that (see the MacPython/matplotlib-wheels README).  For signing, I set up gpg-agent to stash my GPG passphrase: https://gist.github.com/bmhatfield/cc21ec0a3a2df963bffa3c1f884b676b

**Comment by ariddell** [comment]
@WeatherGod @jswhit any comment? Anything I can do to help? If I were to create a ``basemap-wheels`` repo which built wheels for every platform would this be welcome?

Is the main challenge here dealing with building the GEOS library? There aren't any legal barriers to packaging everything into a binary wheel, right?

**Comment by ariddell** [comment]
Oh, this is a dup of #198
