### ISSUE TITLE
drawgreatcirle returns Path objects and not the lines

### ISSUE THREAD

**Issue by krischer** [matplotlib/basemap#322]
This means that they can no longer easily be removed from a map after being drawn. This also violates its own docstring. It's an easy fix but I'm not sure there are other implications to changing this.

Introduced in 35b9207b5ac167f89378a74fc3bd7e8a70e83ae0.

**Comment by WeatherGod** [comment]
You are right, it should be changed back to a Line2D object.

**Comment by krischer** [comment]
Continued in #323.
