### ISSUE TITLE
drawlsmask() results are upside down using backend: cairo

### ISSUE THREAD

**Issue by adrianreber** [matplotlib/basemap#329]
```
from mpl_toolkits.basemap import Basemap
import numpy as np
import numpy as np
import matplotlib.pyplot as plt
m = Basemap(llcrnrlon=-180., llcrnrlat=-90, urcrnrlon=180.,
        urcrnrlat=90.,resolution='c', projection='cyl')
m.drawcoastlines()
m.drawlsmask(ocean_color=(0,0,255,255), land_color=(0,128,0,255), lakes=True)
plt.savefig('test.png')
```

This example with ~/.config/matplotlib/matplotlibrc: backend: cairo gives a map where the result of draslsmask() is upside down:

![test](https://cloud.githubusercontent.com/assets/8724298/21081569/2defb7cc-bfca-11e6-880b-fb27dc32f865.png)

Removing the file ~/.config/matplotlib/matplotlibrc gives a correct result. This is on Fedora 25 with python-basemap-1.0.7-14.fc25.x86_64

Not a real problem for me anymore but just trying to document it if other people are seeing these upside down maps.

**Comment by QuLogic** [comment]
This is a bug with matplotlib matplotlib/matplotlib#7156 that will be fixed in 2.0.0.
