### ISSUE TITLE
GEOS 3.6.0

### ISSUE THREAD

**Issue by micahcochran** [matplotlib/basemap#330]
GEOS 3.6.0 was released on 2016-10-25.  It might not be a bad idea to add it to Travis testing in the next couple months.

**Comment by WeatherGod** [comment]
Indeed, I'll set up a PR to change one of the 3.5.0 tests to use 3.6.0. I can say that the build that uses the nightly python also seems to use the latest numpy, matplotlib and geos, and has been successful as far as I can tell.

As I get ready to get the 1.1.0 release of basemap going, I am thinking that perhaps we should get conda-forge to better handle the geos versioning better. Right now, it still builds using geos 3.3.3, but this conflicts with gdal and friends. I think the conda recipe should probably handle the geos version, much like it does for numpy versions.
