### ISSUE TITLE
Update get_axis_bgcolor

### ISSUE THREAD

**Issue by davidcortesortuno** [matplotlib/basemap#335]
When importing `Basemap`, I get the following Warning:

```
/home/XXX/anaconda3/lib/python3.5/site-packages/mpl_toolkits/basemap/__init__.py:1767:
MatplotlibDeprecationWarning: The get_axis_bgcolor function was deprecated in version 2.0.
Use get_facecolor instead.
  axisbgc = ax.get_axis_bgcolor()
<matplotlib.text.Text at 0x7f1427109128>
```

So I guess the function in `__init__.py` should be updated for being compatible with the newest Matplotlib

**Comment by jenshnielsen** [comment]
It should already do that see https://github.com/matplotlib/basemap/blob/master/lib/mpl_toolkits/basemap/__init__.py#L1753

But that is not in the latest release of basemap which is fairly old. How did you install basemap?

**Comment by davidcortesortuno** [comment]
Oh I didn't notice it in the code. I installed it using `conda`, maybe I just should install using `pip git+...`
I will close this then

**Comment by jenshnielsen** [comment]
No problem, I think the plan is to have a new basemap release soon #293 to fix this
