### ISSUE TITLE
There is no v1.1.0rel tag

### ISSUE THREAD

**Issue by nekketsuuu** [matplotlib/basemap#343]
In [this commit](https://github.com/matplotlib/basemap/commit/dd6d3f606aa72fe6addb8596669c9eb6f9a345bc), `Changelog` says there is a git tag `v1.1.0rel`, but there's not such a tag currently.

I think someone might forget to push it.

**Comment by WeatherGod** [comment]
Indeed, this is because I haven't officially released it. I was planning to
do so shortly after I merged that PR, but life got in the way (as usual).

**Comment by ariddell** [comment]
Is the PyPI size limit a factor here? I know it's not difficult to receive an exception for established projects. (You can make a request in the pypi support forum: https://sourceforge.net/p/pypi/support-requests/ )

**Comment by molinav** [comment]
I am closing this issue, since the topic is a bit outdated now. We have a new stable release (1.3.0). This release is available in PyPI with precompiled binary wheels.
