### ISSUE TITLE
Cannot plot Basemap for Ireland properly

### ISSUE THREAD

**Issue by ktiwari9** [matplotlib/basemap#355]
Hi there,
I am using the shapefile for Ireland available from [here](http://www.arcgis.com/home/item.html?id=ae74a8497a1041669a9d2165a0f450b6) and I am trying to plot a Basemap.

My script looks like this:

```## Create the figure instance
fig = plt.figure(figsize = (5,5))
# rect [left, bottom, width, height]  
ax = fig.add_axes([0.1,0.1,0.9,0.9], frameon=False)
ax.set_axis_bgcolor('white')


MyMap = Basemap(projection='tmerc', lat_0 =  53.866772, lon_0 = -5.23636,satellite_height=300,
        llcrnrlon=-10.65073, llcrnrlat=51.16209,urcrnrlon=  -5.372477, urcrnrlat=55.507785)


# load the shapefile, use the name 'states'
MyMap.readshapefile('../shp/IRL_adm_shp/IRL_adm1', name='borders', drawbounds=True)

# associate this axes with the Basemap instance.
#MyMap.ax = ax

# ### Define the bounding polygon
polys = []
for nshape,seg in enumerate(MyMap.borders):
    if nshape == 17 : #This nshape denotes the large continental body of the northern Ireland
        mainseg1 = seg
        mainpoly1 = Polygon(mainseg1,facecolor='none',edgecolor='r')
        
###### We cannot set 2 clip paths. We need to do a cascade union of these polygons to get a polygon
###### over entire ireland like we have for USA. Then we can clip the point lying outside this region.
ax.set_clip_path(mainpoly1)

## Define a test point
testLat = 52.79531
testLong = -6.25078
testX,testY = MyMap(testLong,testLat)
MyMap.plot(testX,testY,'g*',markersize=12)


# # plt.savefig("../Figures/OzoneGT_test.png", bbox_inches='tight', pad_inches=.2, format="png", dpi=1000)
ax.add_patch(mainpoly1)
MyMap.fillcontinents(color='coral',lake_color='aqua')

#ax.add_patch(mainpoly2)
plt.title("Map of Ireland")
plt.show()

### Test if point is  on land
print(MyMap.is_land(testX,testY))
```

My output looks like this:

![screenshot from 2017-05-18 17 31 44](https://cloud.githubusercontent.com/assets/5789469/26193324/f0963ce6-3bef-11e7-99f2-7b51a9581827.png)

As can be seen from the attached figure, I have 2 **problems**:
1.) The `fillcontinents()` does not fill the polygons properly
2.) the point labeled by the green star is well within Ireland but when I evaluate it using `is_land()` I get the output as false.

I have been trying to solve this problem for quite a while but I have not been able to fix this issue.

**Comment by WeatherGod** [comment]
Both problems are probably caused by using the default resolution dataset,
which is the lowest resolution available. Possible values of the
"resolution" kwarg for the Basemap constructor are (in increasing
resolution): 'c','l','i','h' or 'f'.

**Comment by ktiwari9** [comment]
I thought so too. I tried all resolutions but nothing changes still.

**Comment by guziy** [comment]
Hi @ktiwari9:

Here is how your code works for me

https://github.com/guziy/PyNotebooks/blob/master/basemap_issue_%23355.ipynb

with the resolution="f"

Is it still wrong?

Cheers

**Comment by WeatherGod** [comment]
Setting the resolution to 'i' made the fillcontinent() call work quite well
for me. Have you tried executing your code in a fresh session (in case
there is some sort of cache)?

**Comment by ktiwari9** [comment]
Yeah you were right. Because of cache memory I was still seeing the wrong output. What you showed in your notebook  is exactly what I wanted. Thanks for helping.

P.S. Is there any way to delete all the cache at the begininning of a session using some commands within the noteboook itself ?

**Comment by guziy** [comment]
I am not aware if you can clear browser's cache from the notebook... But I have never experienced problems with that (I am using Chrome). Every time you rerun the output should be updated...

But if you are worried about clearing memory after previous runs, the only way I know is to restart the kernel...

Cheers

**Comment by ktiwari9** [comment]
Thanks for helping out.
