### ISSUE TITLE
Basemap causes Python's kernel to die

### ISSUE THREAD

**Issue by khider** [matplotlib/basemap#363]
I have several functions that use Basemap (and worked well until a week ago). Not everytime basemap is called, the kernel in iPython (Jupyter Notebook or Spyder).

In a terminal, I get the following error:

//anaconda/lib/python3.5/site-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
//anaconda/lib/python3.5/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
GEOS_ERROR: b'IllegalArgumentException: Points of LinearRing do not form a closed linestring'
GEOS_ERROR: b'Shell is not a LinearRing'
Segmentation fault: 11

**Comment by WeatherGod** [comment]
how was basemap installed? Also, is this linux or mac?

Ben Root

**Comment by khider** [comment]
A Mac. The problem was solved when installing through conda

**Comment by WeatherGod** [comment]
Yeah, there are any number of reasons why the python kernel would die.
Without more information, it would be difficult to pin down the cause of
the problem.

I am glad you figured out a work-around, though!
