### ISSUE TITLE
python setup.py install requires copying files to /usr/local/lib/python* dir

### ISSUE THREAD

**Issue by nirandaperera** [matplotlib/basemap#364]
Hi, 

I was following the instructions [1]
but on the last step, 
`python setup.py install`
... fails, because it tries to copy the basemap files to /usr/local/lib/python2*/dist-packages/ dir

Is this a known issue?

so, I used sudo. But then, I had 2 mpl_toolkits in the classpath 1. /usr/local/lib/python2*/dist-packages/  2. ~/.local/lib/python2*/site-packages/ 
then, it is unable to find the basemap. so, I copied all the contents from the /usr/local/lib/python2*/dist-packages/mpl_toolkits to ~/.local/lib/python2*/site-packages/mpl_toolkits dir & now it works properly now. 

[1] https://matplotlib.org/basemap/users/installing.html

**Comment by jenshnielsen** [comment]
I think you can pass `--user` when you do `setup.py install` and it will install to your user directory. I don't think this is basemap specific. All packages will normally install to an os wide dir but you can modify that with command line arguments

**Comment by megies** [comment]
This is definitely not basemap specific but a generic Python installation/environments misconception.

+1 for closing
