### ISSUE TITLE
What is the reason for manual installation?

### ISSUE THREAD

**Issue by juliohm** [matplotlib/basemap#372]
Could you please explain why not pip? Is it because basemap is an unofficial submodule of matplotlib?

**Comment by WeatherGod** [comment]
It is because conda-forge is now the recommended method for installing
basemap.

**Comment by juliohm** [comment]
So pip is considered outdated in the Python community nowadays? I don't use Python in a while (since Julia came out).

**Comment by matthew-brett** [comment]
Oh dear - no - pip is still alive and well, and widely used.   Is there a practical reason for not having a pip release of basemap?

**Comment by matthew-brett** [comment]
I should say that until recently there was segment of the community that thought conda could / should replace pip, but I think that time has passed now; both the pip and conda folks seem to have come to the conclusion that both will be around for a long time.

**Comment by WeatherGod** [comment]
The reason is mostly time constraints for me. Conda-forge automatically
makes the packages for me. Furthermore, the binary dependency on geos gets
tricky to deal with through wheels, and I honestly have zero hours to
dedicate to this project.

**Comment by matthew-brett** [comment]
Aha - yes - that makes sense - I see you need a compiled libgeos C library.   That should be pretty simple to sort out.  I can make a wheel building repo, and maintain it.  Is that OK with you?

**Comment by WeatherGod** [comment]
By all means, please.

**Comment by juliohm** [comment]
Thank you for answering this question.
