### ISSUE TITLE
Deprecation warning for np.readfromstring 

### ISSUE THREAD

**Issue by scollis** [matplotlib/basemap#385]
Seems to both be in __init__
 b = np.array(np.fromstring(polystring,dtype='<f4'),'f8')
/home/travis/miniconda3/envs/testenv/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py:1303: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead

**Comment by WeatherGod** [comment]
so, is it just a straight-out replacement of fromstring to frombuffer? Any py3k stuff I have to worry about?

**Comment by scollis** [comment]
Not that I have seen from Py-ART. I am a bit nervous but I tested all our reads and they worked..
All care no responsibility.

How often do you cut a new conda package? This creates some long travis logs :)

**Comment by WeatherGod** [comment]
I just let conda-forge automatically(?) do it. Remember, people are supposed to be getting off of basemap and using cartopy!

**Comment by scollis** [comment]
Oh! I know @WeatherGod 
The only reason I did not catch this before CI did on Py-ART is I do not use any of the basemap hooks we have.. Completely Cartopy for me! This will serve as a nice lesson to our users though, I will be sure to send the word

**Comment by scollis** [comment]
Let me know if you want @zssherman or I to submit the PR
