### ISSUE TITLE
readshapefile fails on std99d00

### ISSUE THREAD

**Issue by nzqo** [matplotlib/basemap#390]
I just installed basemap via conda and wanted to run your [examples/fillstates.py ](https://github.com/matplotlib/basemap/blob/master/examples/fillstates.py) to plot a map of the US. However, on the following line:
```
shp_info = m.readshapefile('st99_d00','states',drawbounds=True,
                           linewidth=0.45,color='gray')
```

I receive the error:

> Traceback (most recent call last):
>   File "<string>", line 162, in <module>
>   File "/Users/user/anaconda/lib/python3.5/site-packages/mpl_toolkits/basemap/__init__.py", line 2124, in readshapefile
>     raise IOError('cannot locate %s.shp'%shapefile)
> OSError: cannot locate st99_d00.shp

Couldn't find any fix or open issue for this, so sorry if I just didn't see it. Any idea what's going on?

**Comment by QuLogic** [comment]
It's [in the example directory](https://github.com/matplotlib/basemap/blob/master/examples/st99_d00.shp) (+ the other files with the same prefix).

**Comment by MoreYoungGavin** [comment]
i am also see the same issue

**Comment by molinav** [comment]
@GavinMoreYoung As mentioned by @QuLogic, the 'st99_d00' files are part of the `basemap` examples, and they are located in the `examples` folder within this repository. They do not come with a standard installation of `basemap`, so you will need to download them from the repository if you want to use them (and write the appropriate path to them in your script).

**Comment by GavinMoreYoung** [comment]
收到，会尽快给您回复。

**Comment by molinav** [comment]
@nzqo The most likely reason for your error is if you have run the example from outside the `examples` folder. Note that the 'st99_d00' files can be found inside the `examples` folder, and your snippet is using relative paths (i.e. assuming that you are running this code inside the `examples` folder).
