### ISSUE TITLE
streamplot issue with basemap

### ISSUE THREAD

**Issue by tdiliberto** [matplotlib/basemap#391]
Hello,

Moved jobs and am setting up anaconda python3.6 version on my new computer. 

I've installed matplotlib, netcdf4, numpy, and basemap.

However, once I run code that plots streamlines using streamplot that worked on my previous computer, I get an error. (Note that I also got the same error code when I installed python2.7). @DaRothen has tried to help and pointed me here. I've attached the code but also have pasted the relevant sections. At the bottom is the error code I received.

[plot_stream.txt](https://github.com/matplotlib/basemap/files/1776330/plot_stream.txt)

import numpy as np
import numpy.ma as ma
import matplotlib.pylab as plt
from netCDF4 import Dataset as ds
import matplotlib as mpl
from mpl_toolkits.basemap import Basemap 
import sys

fig=plt.figure(figsize=(10,7),frameon=False)
plt.axis('off')
fig.set_size_inches(24.80,9.92)
fig.set_dpi(100)

norm=mpl.colors.Normalize(vmin=mgntd.min(),vmax=mgntd.max())

#Original
m=Basemap(llcrnrlon=130,llcrnrlat=0,urcrnrlon=300,urcrnrlat=75,width=4096,height=2048,projection='cyl',resolution='c',
          area_thresh=50000)

m.drawcoastlines(linewidth=.5,color='0.75')
m.drawcountries(linewidth=.5,color='0.75')
m.drawmapboundary(fill_color='white')

m.streamplot(xclip,yclip,uclip,vclip,density=4,linewidth=lw,color=mgntd,cmap=cm,
             arrowsize=1,
             arrowstyle='->,head_length=.5,head_width=.5',
             minlength=.05, hold=None)

plt.savefig('wind300tot_2021Feb2018.png',format='png',dpi=100,orientation='landscape',
               transparent='True',bbox_inches='tight',pad_inches=0.)

plt.show()

ERROR:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\Anaconda3\envs\mpl_test\lib\site-packages\mpl_toolkits\basemap\__init__.py in _cliplimb(self, ax, coll)
   1812         try:
-> 1813             coll.set_clip_path(c)
   1814         except:

AttributeError: 'StreamplotSet' object has no attribute 'set_clip_path'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-11-4b198cc3b544> in <module>()
     28              arrowsize=1,
     29              arrowstyle='->,head_length=.5,head_width=.5',
---> 30              minlength=.05, hold=None)
     31 
     32 

~\Anaconda3\envs\mpl_test\lib\site-packages\mpl_toolkits\basemap\__init__.py in with_transform(self, x, y, u, v, *args, **kwargs)
    573             # convert lat/lon coords to map projection coords.
    574             x, y = self(x,y)
--> 575         return plotfunc(self,x,y,u,v,*args,**kwargs)
    576     return with_transform
    577 

~\Anaconda3\envs\mpl_test\lib\site-packages\mpl_toolkits\basemap\__init__.py in streamplot(self, x, y, u, v, *args, **kwargs)
   3738         self.set_axes_limits(ax=ax)
   3739         # clip to map limbs
-> 3740         ret,c = self._cliplimb(ax,ret)
   3741         # streamplot arrows not returned in matplotlib 1.1.1, so clip all
   3742         # FancyArrow patches attached to axes instance.

~\Anaconda3\envs\mpl_test\lib\site-packages\mpl_toolkits\basemap\__init__.py in _cliplimb(self, ax, coll)
   1813             coll.set_clip_path(c)
   1814         except:
-> 1815             for item in coll:
   1816                 item.set_clip_path(c)
   1817         return coll,c

TypeError: 'StreamplotSet' object is not iterable

**Comment by WeatherGod** [comment]
wow, that is a nasty bug. I'll have to dig a bit to figure out how to solve
this correctly.

**Comment by WeatherGod** [comment]
Figured out the source of the problem (and why I didn't notice it before). I created #392 to fix this.

**Comment by tdiliberto** [comment]
Thanks! I applied the fix and it worked perfectly.
