### ISSUE TITLE
AttributeError: 'Axes' object has no attribute 'get_axis_bgcolor'

### ISSUE THREAD

**Issue by sebhahn** [matplotlib/basemap#395]
Since [matplotlib 2.2.0 the API](https://matplotlib.org/api/api_changes.html#removals) has changed:

> The Axes.get_axis_bgcolor, Axes.set_axis_bgcolor, Bbox.update_from_data, box.update_datalim_numerix, MaxNLocator.bin_boundaries methods have been removed.

and basemap throws the exception:

`AttributeError: 'Axes' object has no attribute 'get_axis_bgcolor'`

Is it possible to fix this easily?

**Comment by efiring** [comment]
I think it is already fixed; the only references to 'get_axis_bgcolor' that I find are protected by a check of the matplotlib version.  What version of basemap are you using?

**Comment by sebhahn** [comment]
I'm using basemap 1.0.7, which comes with `conda install basemap`, but I just saw that conda forge holds version 1.1.0, I guess that's the one you refer to

**Comment by efiring** [comment]
Yes, that's the one to use.

**Comment by ocefpaf** [comment]
@sebhahn note that in conda-forge we have separate packages for basemap and the bundle high resolution data. If you need both you can install them with:

```shell
conda install --channel conda-forge install basemap basemap-data-hires
```

If you do not need the extra 100 MB of high resolution data you can just install `basemap`.

**Comment by sebhahn** [comment]
Thanks everybody!
