### ISSUE TITLE
Eliminate 2to3

### ISSUE THREAD

**Issue by efiring** [matplotlib/basemap#399]
The use of 2to3 in setup.py means we can't do an editable install.  It looks like it might be very easy to eliminate the use of 2to3.  @WeatherGod, have you looked at this, and if so, do you see any difficulty with it?

Two options:

1) Make the code compatible with 2 and 3 without using 2to3 in setup.py.  It looks like this requires little more than fixing print statements and using six, or a direct conditional, to handle urllib imports.

2) Skip the compatibility and make a 3-only release, matching matplotlib's.

Thoughts?

**Comment by WeatherGod** [comment]
If you want to go for option 1, go right ahead. My main concern is that the
test suite just isn't comprehensive enough to verify the efforts.
Especially given the planned EoL for basemap. If someone else wants to take
up the mantle, I won't stop them, though.

**Comment by ocefpaf** [comment]
Even though I'm inclined for option `2` b/c it would simplify the code base, make it easier to maintain, etc, my guess is that `basemap` users are mostly stuck with `Python 2.7`. I believe that those moving to `Python 3` are also moving to `cartopy`.

With that said I think I can help with option `1`, I can send some PRs if that is the direction you want to go.

**Comment by efiring** [comment]
@ocefpaf Let's do option 1; I don't think option 2 would be so very different, so it's not urgent.  I tried running 2to3 on __init__, where most of the code is, and it didn't do much--and much of what it did was not necessarily, at least if the python3 target is 3.5 or higher, so that the `u'...'` strings can be left in.  If 2to3 in setup.py is not doing any more than what I see in this default run, it looks like eliminating it requires changing only a few lines.  I would welcome your PR.

**Comment by ocefpaf** [comment]
OK. I'll get to it ASAP.
