### ISSUE TITLE
publish v1.1.0 to pypi

### ISSUE THREAD

**Issue by alaniwi** [matplotlib/basemap#403]
1.1.0 has been tagged in github but isn't being picked up by default during pip install (latest on pypi seems to be 1.0.7). Unless there is a good reason not to, please can it be published to pypi?

**Comment by t-makaro** [comment]
And as a conda package too. Currently, the only conda packages of basemap 1.0.7 are for python 2.7 and Numpy1.10, but I'd like to be able to install on python 3.6

**Comment by WeatherGod** [comment]
The "official" conda packages for basemap is on the conda-forge channel. I
have no control over the packages on the standard channel. The conda-forge
channel pretty much tracks the master branch (not quite, but it gets all of
the important stuff).

**Comment by heitorPB** [comment]
Could you publish version 1.2.0 on pypi?

**Comment by molinav** [comment]
@heitorPB If you are using GNU/Linux, you may find pre-compiled binary wheels in PyPI for the current beta release (1.3.0b1), I just uploaded them yesterday. The stable release 1.3.0 will come with some reorganisation (splitting `basemap` into `basemap`, `basemap-data` and `basemap-data-hires`). For the moment you could do:
```sh
python -m pip install "basemap-data == 1.3.0b1" "basemap == 1.3.0b1"
```
You only need `basemap-data-hires` if you need the high-resolution data assets (i.e. those labelled with "h" and "f").

**Comment by molinav** [comment]
@heitorPB I just bring you the nice update that we have stable release for `basemap` version 1.3.0. So now we can just install `basemap` with `pip` as we would do with any other package:
```sh
python -m pip install basemap
```

**Comment by heitorPB** [comment]
Thanks!
