### ISSUE TITLE
Plot 2 out of 3 dimensions

### ISSUE THREAD

**Issue by ameanijon** [matplotlib/basemap#413]
I have a netCDF file and I'm trying to plot shear on a map. 

Entering `<cs = m.contourf(xx,yy,shear,clevs,cmap='inferno', latlon=True)>` gives `<ValueError: 1-d or 2-d data required>`. When printing the shape of my parameter (shear), it gives three dimensions: (1460, 241, 480), which are respectively time, latitude and longitude. Obviously I don't want to plot the time on this map, just shear with lon and lat. Is there a way I can get basemap to ignore the time dimension?

**Comment by WeatherGod** [comment]
you need to index your data. So, something like `cs = m.contourf(xx, yy,
shear[0], clevs, cmap='inferno', latlon=True)`.

**Comment by ameanijon** [comment]
@WeatherGod Fantastic! That worked and was a lot easier than I expected. Thanks a lot! :)
