### ISSUE TITLE
Basemap Can't work well in pywin32  

### ISSUE THREAD

**Issue by Athenaplot** [matplotlib/basemap#425]
I writed a window Service using pywin32, In the Service , I use Basemap to draw a map of B,but it can't work.

<img width="797" alt="1537883575 1" src="https://user-images.githubusercontent.com/31769682/46018883-78c96400-c10d-11e8-98b5-dbe56640b150.png">

the code is like above. the code in red block can work,but when it comes to the green block, the code can't go on , in other word , the code doesn't post a error message , so the procedure isn't killed. just like freeze.
<img width="386" alt="1537885195 1" src="https://user-images.githubusercontent.com/31769682/46020523-2d18b980-c111-11e8-8066-09dde9e9756a.png">

the window Service written by Python is just like above.
but ,when i put the code as a Python Script,just like below:
<img width="1192" alt="1537884933 1" src="https://user-images.githubusercontent.com/31769682/46020297-9ea43800-c110-11e8-89c1-1af2c0becb3b.png">

it can work well.
I want my code for the window Service work well .  is there anyone can help me out?

**Comment by WeatherGod** [comment]
I don't know much about windows services, but I will point out an
observation. The call to `map_B.readshapefile(...)` in your service code
will implicitly trigger a window creation via matplotlib. Depending on how
your install is done and other things, this means a GUI framework is
triggered. I don't know if that is allowed within a service. Perhaps if you
added something along the lines of:
```
import matplotlib
matplotlib.use('agg')
```
at the top of the script to force a non-interactive backend, maybe the hang
will go away?
