### ISSUE TITLE
New matplotlib (3.0) breaks Basemap

### ISSUE THREAD

**Issue by lukelbd** [matplotlib/basemap#434]
We just need a couple lines commented out.

The `matplotlib.cbook` function `is_scalar` no longer exists. It is only used once in `__init__.py`. I recommend replacing it with something like `from number import Number`, and then where `is_scalar` was called, instead use `isinstance(value, Number)`. Or something like `hasattr(value, '__iter__')`.

Thanks in advance

**Comment by WeatherGod** [comment]
This has already been fixed. Note that the latest versions of basemap are now distributed through conda-forge, not pypi.

**Comment by sandrotosi** [comment]
@WeatherGod please remember there are downstream packagers too; releasing only on conda-forge makes our lives harder (but at least we can fetch the tagged release from GH)
