### ISSUE TITLE
please provide way to regenerate cython files

### ISSUE THREAD

**Issue by juliantaylor** [matplotlib/basemap#436]
The release tarballs contain generated cython files. But sometimes you want to regenerate them with newer versions of cython e.g. to support newer python versions.

Please provide a way to correctly generate all files. E.g. via a script (that is aware of cython -2 and cython -3) or directly via setup.py like e.g. python-numpy and python-scipy do it (see their cythonize.py).

**Comment by molinav** [comment]
@juliantaylor I have been refactoring the whole project and now the `_geoslib.c` file is not part of the repository anymore, i.e. the Cython extension is compiled at build time when calling `python setup.py bdist_wheel`.

If you are using GNU/Linux, I recently uploaded precompiled binary wheels to PyPI with the latest beta release (1.3.0b1). Soon we will have a stable release.

**Comment by molinav** [comment]
@juliantaylor We finally have the stable release 1.3.0 on PyPI in case you want to give it a try.
