### ISSUE TITLE
Basemap 1.2.0 reports itself as 1.1.0

### ISSUE THREAD

**Issue by danson930923** [matplotlib/basemap#446]
Hello Team,

I installed basemap v1.2.0 with conda install. After installing, I wanted to check the version, but it kept reporting it is version 1.1.0.

I wonder if the following code may be the reason why it was reporting v1.1.0
https://github.com/matplotlib/basemap/blob/v1.2.0rel/lib/mpl_toolkits/basemap/__init__.py#L61

Thank you

**Comment by WeatherGod** [comment]
Whoops...

Yeah, I'll fix that. Note, it shouldn't cause any actual issues as that
attribute isn't actually used anywhere (unless code elsewhere is checking
that attribute...)

**Comment by WeatherGod** [comment]
This is now fixed in master. Don't know if it makes sense to re-tag as v1.2.0rel or not.
