### ISSUE TITLE
v1.2.0rel：No module named 'mpl_toolkits.basemap'

### ISSUE THREAD

**Issue by ZezhiShau** [matplotlib/basemap#450]
There comes an error when i tried to 
```python
from mpl_toolkits.basemap import Basemap
```
saying: `No module named 'mpl_toolkits.basemap'`
But when i run a commond `sudo -H  pip install -U git+https://github.com/matplotlib/basemap.git` to "update" my basemap and do the same work, the error disappears. is v1.2.3rel the latest version?

**Comment by WeatherGod** [comment]
v1.2.0rel is the latest release. Also, please do not do `sudo pip install`.
Use virtualenv or conda or some other environment management tool. Most
likely, your environment is somehow corrupted because you are mucking about
with the system python.
