### ISSUE TITLE
pyproj has no attribute pyproj_datadir

### ISSUE THREAD

**Issue by andre-fu** [matplotlib/basemap#457]
Installed basemap via pip 
`pip3 install --user git+https://github.com/matplotlib/basemap.git`

```
from mpl_tooklits.basemap import Basemap
```
I get the error `module 'pyproj' has no attribute 'pyproj_datadir' `
found here https://imgur.com/QauL5NI

Any advice on how to resolve this? I tried going into the pyproj folder and change the `__init__.py` from `pyproj_datadir` to just `datadir`. That led to more errors, so I reversed that. I'd like to not change the source files too much.

**Comment by andre-fu** [comment]
Install `pyproj 1.9.6` to use basemap

**Comment by sscherfke** [comment]
The issue has to be fixed nonetheless.
