### ISSUE TITLE
unexpected end of file error w/ basemap-1.2.0

### ISSUE THREAD

**Issue by bruhwiler** [matplotlib/basemap#464]
I see this with both the 1.2.0 and 1.1.0 tarballs linked from the download page,
https://github.com/matplotlib/basemap/releases/
although the end of file error occurs at different points in the file.

I'm working on Fedora 29

Here is a screenshot:
![image](https://user-images.githubusercontent.com/3825435/60400104-a031df00-9b2c-11e9-8f76-fe882912ad16.png)

**Comment by bruhwiler** [comment]
I tried the 1.2.0 and 1.1.0 *.zip files as well, and I get the following error when trying to unzip them on Fedora 29:

![image](https://user-images.githubusercontent.com/3825435/60400169-a07eaa00-9b2d-11e9-86a6-82d539256c40.png)

**Comment by WeatherGod** [comment]
What are your checksums? Most likely, the downloads were corrupted, because
those tarballs have been up for several years.

**Comment by bruhwiler** [comment]
Thanks @WeatherGod 
You're probably right.

As a work around, I'm cloning the GitHub repo and skipping the tarballs.

Closing the issue.
