### ISSUE TITLE
Cannot normalize pcolormesh colors

### ISSUE THREAD

**Issue by ricitron** [matplotlib/basemap#468]
I cannot normalize the colors on a pcolormesh plot. 

For example, I can usually normalize a colormap:
plt.imshow(data,vmin=-4,vmax=4,cmap=plt.cmap.jet)

However, when using the pcolormesh basemap plotting feature, I cannot normalize the data:
m1.pcolormesh(lons,lats,data,shading='flat',cmap=plt.cm.jet,vmin=-4,vmax=4,latlon=True,rasterized=True)

The data simply remains normalized to the max and min value of the data. I've tried using mcolors.Normailze and setting the norm parameter in pcolormesh, and also tried changing the clim values, but nothing works. No matter what when plotting pcolormesh on a basemap I cannot change the normalization of the colormap.

**Comment by WeatherGod** [comment]
I doubt this is a basemap issue. Basemap just passes keyword arguments down
to the regular pcolormesh method, only first taking care of transforming
coordinates. I bet the "shading='flat'" argument is causing issues.

**Comment by efiring** [comment]
`shading='flat'` is just specifying a valid option that is in fact the default, so it's hard to see how that would cause a problem.

@ricitron, would you provide a very simple, clear, and self-contained example, please, so we can reproduce it?   The shorter and simpler, the better.
