### ISSUE TITLE
MatplotlibDeprecationWarning of Matplotlib v3.1

### ISSUE THREAD

**Issue by jiaozhh** [matplotlib/basemap#469]
After installing Matplotlib v3.1, the MatplotlibDeprecationWarning always comes out when using the basemap v1.2. The following is an example: 
``` python
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap

# setup Lambert Conformal basemap.
m = Basemap(width=12000000, height=9000000, projection='lcc',
            resolution='c', lat_1=45., lat_2=55, lat_0=50, lon_0=-107.)
# draw coastlines.
m.drawcoastlines()
# draw a boundary around the map, fill the background.
# this background will end up being the ocean color, since
# the continents will be drawn on top.
m.drawmapboundary(fill_color='aqua')
# fill continents, set lake color same as ocean color.
m.fillcontinents(color='coral', lake_color='aqua')
plt.show()
```
The warming message is as follows: 

> tmp.py:10: MatplotlibDeprecationWarning: 
The dedent function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use inspect.cleandoc instead.
  resolution='c', lat_1=45., lat_2=55, lat_0=50, lon_0=-107.)

Please fix this issue.  Thank you!

**Comment by WeatherGod** [comment]
Already fixed in master.
