### ISSUE TITLE
Bug fix suggestion: How to get around `KeyError: 'PROJ_LIB'` 

### ISSUE THREAD

**Issue by jolespin** [matplotlib/basemap#483]
![image](https://user-images.githubusercontent.com/9061708/73399235-bd35b880-429b-11ea-85f2-837fceedc183.png)
Here's my `basemap` installation via `conda`:

```
(soothsayer_env) Joshs-MacBook-Pro:barrnap_output mu$ conda info basemap=1.2.1=py36hd103db2_1

basemap 1.2.1 py36hd103db2_1
----------------------------
file name   : basemap-1.2.1-py36hd103db2_1.tar.bz2
name        : basemap
version     : 1.2.1
build string: py36hd103db2_1
build number: 1
channel     : https://conda.anaconda.org/conda-forge/osx-64
size        : 15.2 MB
arch        : None
constrains  : ()
license     : MIT
md5         : 9dc5c6ef11367338aeb7b06d68eb0544
platform    : None
sha256      : 330ec53b50a1f5b7c1612de1058aa0122e862aa0b1e6aa0813013a7c21c762dc
subdir      : osx-64
timestamp   : 1565723626559
url         : https://conda.anaconda.org/conda-forge/osx-64/basemap-1.2.1-py36hd103db2_1.tar.bz2
dependencies:
    geos >=3.7.2,<3.7.3.0a0
    libcxx >=4.0.1
    matplotlib-base >=1.0.0,!=3.0.1
    numpy >=1.14.6,<2.0a0
    proj4 >=4.9.3,<6
    proj4 >=5.2.0,<5.2.1.0a0
    pyproj >=1.9.3
    pyshp >=1.2.0
    python >=3.6,<3.7.0a0
    six
WARNING: 'conda info package_name' is deprecated.
          Use 'conda search package_name --info'.
```

Essentially, it doesn't know where to look for `PROJ_LIB` so I set the environment variable and it works now.

**Comment by molinav** [comment]
The upstream code does not have this line anymore, but I remember that once I had to solve this problem by manually replacing it in the `__init__.py` file from
```python
pyproj_datadir = os.environ['PROJ_LIB']
```
into
```python
if 'PROJ_LIB' in os.environ:
    pyproj_datadir = os.environ['PROJ_LIB']
else:
    pyproj_datadir = pyproj.datadir.pyproj_datadir
```
since `pyproj` is already imported at the very beginning and provides the `PROJ_LIB` path as attribute.

**Comment by jolespin** [comment]
Has this been fixed in the current version?

**Comment by molinav** [comment]
In the most recent version (v1.2.1), the `pyproj_datadir` variable is not there anymore. I think that `basemap` now relies on `pyproj` itself finding the location of the PROJ library, and if it is not found then `pyproj` will complain.

**Comment by molinav** [comment]
I have been diving a bit more into this. In fact, `PROJ_LIB` has been already gone for some time from `basemap`, but later it is being re-added by the Anaconda maintainers in the Anaconda `basemap` package. Take a look at the `basemap-feedstock` repository that is building `basemap` for Anaconda:
https://github.com/conda-forge/basemap-feedstock

You will see that they are applying a [patch](https://github.com/conda-forge/basemap-feedstock/blob/master/recipe/data.patch) that removes some part of the new `basemap` code and resets the old code that was using `PROJ_LIB`:
```diff
@@ -154,7 +149,8 @@
              }
 
 # create dictionary that maps epsg codes to Basemap kwargs.
-epsgf = open(os.path.join(basemap_datadir, 'epsg'))
+pyproj_datadir = os.environ['PROJ_LIB']
+epsgf = open(os.path.join(basemap_datadir,'epsg'))
 epsg_dict={}
 for line in epsgf:
     if line.startswith("#"):
```
So it seems it is a specific problem of the Anaconda packaging.

**Comment by molinav** [comment]
I am closing this since it was a problem on how Anaconda is packaging `basemap` and not a problem of `basemap` itself.
