### ISSUE TITLE
Issue when call basemap

### ISSUE THREAD

**Issue by jeff22222** [matplotlib/basemap#490]
I installed Basemap by
`pip install --user git+https://github.com/matplotlib/basemap.git`
but when I called library
`from mpl_toolkits.basemap import Basemap`
It showed erro

```
----> 2 from mpl_toolkits.basemap import Basemap
      3 import matplotlib.pyplot as plt
      4 
      5 plt.rcParams["font.size"] = 20

ModuleNotFoundError: No module named 'mpl_toolkits.basemap'
```

**Comment by WeatherGod** [comment]
Most likely, either the install failed in a subtle way, or the package got installed into a different environment than what you are running.

Please remember that Basemap isn't really supported anymore and has been deprecated for several years. Please try and use Cartopy where possible.
