### ISSUE TITLE
Installing GEOS on windows

### ISSUE THREAD

**Issue by LSRathore** [matplotlib/basemap#491]
I am trying to install geos on windows 10 using cygwin. When `make` command is given, it shows:
`make: *** No targets specified and no makefile found.  Stop.`
I am unable to install in on my system so I tried it with `pip`. The `pip` installed geos, but basemap can not find the path of 'GEOS_DIR`.
How can I download basemap?

**Comment by lokendrarathore** [comment]
The `python setup.py install` for basemap gives the following error:
```
checking for GEOS lib in C:\Users\lsrathore ....
checking for GEOS lib in C:\Users\lsrathore\local ....
checking for GEOS lib in /usr ....
checking for GEOS lib in /usr/local ....
checking for GEOS lib in /sw ....
checking for GEOS lib in /opt ....
checking for GEOS lib in /opt/local ....

Can't find geos library in standard locations ('C:\Users\lsrathore', 'C:\Users\lsrathore\local', '/usr', '/usr/local', '/sw', '/opt', '/opt/local').
Please install the corresponding packages using your
systems software management system (e.g. for Debian Linux do:
'apt-get install libgeos-3.3.3 libgeos-c1 libgeos-dev' and/or
set the environment variable GEOS_DIR to point to the location
where geos is installed (for example, if geos_c.h
is in /usr/local/include, and libgeos_c is in /usr/local/lib,
set GEOS_DIR to /usr/local), or edit the setup.py script
manually and set the variable GEOS_dir (right after the line
that says "set GEOS_dir manually here".
```

**Comment by joernu76** [comment]
I would recommend using anaconda to use basemap under windows using conda-forge. That should settle a lot of problems (basemap does not work with the most recent matplotlib version, see issue 495, installing a slightly older one should work, though).

**Comment by molinav** [comment]
If you want to work with a direct installation of Python without Anaconda under Windows, you may also use the wheel files generated by C. Gohlke available in https://www.lfd.uci.edu/~gohlke/pythonlibs/#basemap since they already provide the GEOS DLL for Windows. You can install them with `pip` by passing the direct path to the downloaded wheel file.

In the mid term I would like to upload such kind of wheels to PyPI, but I am currently doing a bit of refactoring first.

**Comment by molinav** [comment]
Finally (after one year!) we have precompiled binary wheels for Windows and GNU/Linux which can be installed with `pip`:
```sh
python -m pip install basemap
```
I am closing this issue now. Feel free to open a new issue if there are still problems with getting `basemap` work on Windows.
