### ISSUE TITLE
Python3.7 basemap error with nsper projection at latitudes above 45 north

### ISSUE THREAD

**Issue by qianwu2** [matplotlib/basemap#504]
Hi
When I use the basemap nsper project at latitude north of 45 I got this error.   If I lower that latitude to less 45N, it works fine.

>>> m=Basemap(projection='nsper',satellite_height=30000000.,lat_0=50,lon_0=-50,resolution='l')
GEOS_ERROR: b'IllegalArgumentException: CGAlgorithmsDD::orientationIndex encountered NaN/Inf numbers'
zsh: segmentation fault  python3.7

**Comment by jklymak** [comment]
`basemap` is no longer actively maintained, so it is unlikely this will be fixed.  Please consider migrating to cartopy

**Comment by fragkoul** [comment]
People keep pushing us to cartopy, but there are still things one can only do with basemap.

**Comment by jklymak** [comment]
Again, basemap is no longer actively maintained, so submitting issues here won't lead to solutions.  1) anyone can make a fork and maintain it themselves, or 2) cartopy will certainly take feature requests and pull requests to try to add features that are needed, particularly if they are ones that basemap used to supply.
