### ISSUE TITLE
Some possibility of installation

### ISSUE THREAD

**Issue by hydrogencl** [matplotlib/basemap#510]
Dear community, and possible people suffering as well, 

I also have struggles for installing basemap, especially with python3.6 (default shipped with Ubuntu 18.04)
After several tries like using cartopy, using apt install to install cartopy and basemap. None of them works quickly for python3.6. 

In the end it works for this "simple" way:
1) Installing pyproj (3.0.0) by `python3 -m pip install pyproj==3.0` 
2) installing matplotlib by `python3 -m pip install matplotlib==3.3.3` 
3) downloading the basemap 1.2.2 version and install also by `python3 -m pip install .` in the basemap untar folder.

Hope this helps.

**Comment by molinav** [comment]
Hi @metalpen1984,

Yes, you are totally right, at the moment it is not so easy to install due to the `basemap` dependencies. I am working on it but the solution is still not finished.

You could also try some temporary wheels that I have in my [fork](https://github.com/molinav/basemap/releases/tag/v1.3.0). These wheels already handle the installation of the Python dependencies, but it still lacks the pre-built `libgeos` shared library inside in order to have proper `manylinux1` packages. I am also working on it.

With these wheels you would need to install first GEOS by yourself (`sudo apt-get install libgeos-dev`), ensure that you have `gcc` installed too, and then `python3 -m pip install` for the wheel files.

Please note also that I have split `basemap` in several packages there:
- `basemap-lite`: the basemap Python source code, it depends on `basemap-data` so you need to install it first.
- `basemap-data`: most of the files in the data folder.
- `basemap-extras`: the bulky high-resolution data files. This wheel is optional if you do not need the high-resolution files. It is kind of like `basemap-data-hires` in Anaconda.

**Comment by LiXingguangBrandonStark** [comment]
can not install basemap for two days, and i tried many times, who can help me out, thanks.

**Comment by molinav** [comment]
@LiXingguangBrandonStark What operating system are you using?

**Comment by LiXingguangBrandonStark** [comment]
mac

**Comment by LiXingguangBrandonStark** [comment]
(base) lixingguangtekiMacBook-puro:basemap-1.2.2rel lixingguang$ pip list
Package         Version
--------------- ---------
certifi         2020.12.5
cycler          0.10.0
kiwisolver      1.3.1
matplotlib      3.3.3
numpy           1.20.1
Pillow          8.1.0
pip             21.0.1
pyparsing       2.4.7
pyproj          3.0.0
pyshp           2.1.3
python-dateutil 2.8.1
setuptools      49.2.1
six             1.15.0

**Comment by molinav** [comment]
@LiXingguangBrandonStark Unfortunately for Mac I cannot help you much because I do not have a computer with it. I would like to provide wheel files in the future for Windows, Linux and Mac, but I haven't had time yet.

The most likely reason why your installation does not work is because it cannot compile the `_geos` extension, probably because it cannot find the `geos_c` shared library. Do you have GEOS installed in your system? Are you trying to compile GEOS from the source code provided with `basemap`?

**Comment by LiXingguangBrandonStark** [comment]
(base) lixingguangtekiMacBook-puro:basemap-1.2.2rel lixingguang$ pip list
Package         Version
--------------- ---------
basemap-data    1.3.0
certifi         2020.12.5
click           7.1.2
cycler          0.10.0
Flask           1.1.2
geos            0.2.2
itsdangerous    1.1.0
Jinja2          2.11.3
kiwisolver      1.3.1
lxml            4.6.2
MarkupSafe      1.1.1
matplotlib      3.3.3
numpy           1.20.1
Pillow          8.1.0
pip             21.0.1
pyparsing       2.4.7
pyproj          3.0.0
pyshp           2.1.3
python-dateutil 2.8.1
setuptools      49.2.1
six             1.15.0
Werkzeug        1.0.1

**Comment by LiXingguangBrandonStark** [comment]
anyone install basemap in MAC?

**Comment by molinav** [comment]
Sorry, the `geos` I was referring to is not the one that you can see in PyPI (and listed with you `pip list` command), it should be a shared library that e.g. under Ubuntu it can be installed with `apt-get`. If it is not available through repositories, you would need to compile it from source before installing `basemap`. The source code of GEOS is provided together with `basemap`.

Are you using Anaconda? Are you using Homebrew?

**Comment by LiXingguangBrandonStark** [comment]
i can use both of annacoda and homebrew.

**Comment by LiXingguangBrandonStark** [comment]
(base) lixingguangtekiMacBook-puro:basemap-1.2.2rel lixingguang$ python setup.py install
checking for GEOS lib in /Users/lixingguang ....
checking for GEOS lib in /Users/lixingguang/local ....
checking for GEOS lib in /usr ....
checking for GEOS lib in /usr/local ....
GEOS lib (version 3.3.3) found in /usr/local
running install
running bdist_egg
running egg_info
running build_src
build_src
building extension "_geoslib" sources
build_src: building npy-pkg config files
writing requirements to lib/basemap.egg-info/requires.txt
writing lib/basemap.egg-info/PKG-INFO
writing namespace_packages to lib/basemap.egg-info/namespace_packages.txt
writing top-level names to lib/basemap.egg-info/top_level.txt
writing dependency_links to lib/basemap.egg-info/dependency_links.txt
reading manifest file 'lib/basemap.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README'
warning: no files found matching 'LICENSE_proj4'
warning: no files found matching 'LICENSE_pyshp'
warning: no files found matching 'lib/mpl_toolkits/basemap/pyproj.py'
warning: no files found matching 'lib/mpl_toolkits/basemap/shapefile.py'
writing manifest file 'lib/basemap.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
running build_ext

**Comment by LiXingguangBrandonStark** [comment]
when i run "python setup.py install", there are errors.

**Comment by LiXingguangBrandonStark** [comment]
customize UnixCCompiler
customize UnixCCompiler using build_ext
creating build/bdist.macosx-10.7-x86_64/egg
creating build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits
creating build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/cm.py -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/__init__.py -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/test.py -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/diagnostic.py -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/proj.py -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/solar.py -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap
creating build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_2.5min_c.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/UScounties.dbf -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/rivers_l.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/statesmeta_h.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/statesmeta_i.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/statesmeta_l.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_2.5min_f.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/rivers_h.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/rivers_i.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/riversmeta_l.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/states_c.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_10min_c.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/countries_l.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/gshhs_f.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_1.25min_i.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/gshhsmeta_l.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/countriesmeta_i.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/countriesmeta_h.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_5min_c.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_1.25min_h.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_1.25min_l.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/gshhsmeta_i.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/countriesmeta_l.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_5min_f.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/gshhsmeta_h.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/UScounties.shx -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/riversmeta_i.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/states_f.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_10min_f.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/gshhs_c.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/countries_i.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/countries_h.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/riversmeta_h.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/UScounties.shp -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_1.25min_c.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/gshhsmeta_f.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_5min_h.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/countriesmeta_c.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_5min_i.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/riversmeta_f.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/states_i.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_10min_i.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/countries_f.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/gshhs_l.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_10min_h.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/states_h.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/shadedrelief.jpg -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/riversmeta_c.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/states_l.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_10min_l.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/gshhs_i.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/countries_c.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/gshhs_h.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_1.25min_f.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/gshhsmeta_c.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/countriesmeta_f.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_5min_l.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/statesmeta_c.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/bmng.jpg -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_2.5min_i.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/rivers_f.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_2.5min_h.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/lsmask_2.5min_l.bin -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/rivers_c.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/etopo1.jpg -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/UScounties.prj -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/statesmeta_f.dat -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/basemap/data/epsg -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/data
copying build/lib.macosx-10.7-x86_64-2.7/mpl_toolkits/__init__.py -> build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits
copying build/lib.macosx-10.7-x86_64-2.7/_geoslib.so -> build/bdist.macosx-10.7-x86_64/egg
byte-compiling build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/cm.py to cm.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/test.py to test.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/diagnostic.py to diagnostic.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/proj.py to proj.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/basemap/solar.py to solar.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/mpl_toolkits/__init__.py to __init__.pyc
creating stub loader for _geoslib.so
byte-compiling build/bdist.macosx-10.7-x86_64/egg/_geoslib.py to _geoslib.pyc
creating build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying lib/basemap.egg-info/PKG-INFO -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying lib/basemap.egg-info/SOURCES.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying lib/basemap.egg-info/dependency_links.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying lib/basemap.egg-info/namespace_packages.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying lib/basemap.egg-info/requires.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying lib/basemap.egg-info/top_level.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
mpl_toolkits.basemap.__init__: module references __file__
creating 'dist/basemap-1.2.1-py2.7-macosx-10.7-x86_64.egg' and adding 'build/bdist.macosx-10.7-x86_64/egg' to it
removing 'build/bdist.macosx-10.7-x86_64/egg' (and everything under it)
Processing basemap-1.2.1-py2.7-macosx-10.7-x86_64.egg
removing '/Users/lixingguang/opt/anaconda2/lib/python2.7/site-packages/basemap-1.2.1-py2.7-macosx-10.7-x86_64.egg' (and everything under it)
creating /Users/lixingguang/opt/anaconda2/lib/python2.7/site-packages/basemap-1.2.1-py2.7-macosx-10.7-x86_64.egg
Extracting basemap-1.2.1-py2.7-macosx-10.7-x86_64.egg to /Users/lixingguang/opt/anaconda2/lib/python2.7/site-packages
basemap 1.2.1 is already the active version in easy-install.pth

**Comment by LiXingguangBrandonStark** [comment]
Installed /Users/lixingguang/opt/anaconda2/lib/python2.7/site-packages/basemap-1.2.1-py2.7-macosx-10.7-x86_64.egg
Processing dependencies for basemap==1.2.1
Searching for pyproj>=1.9.3
Reading https://pypi.org/simple/pyproj/

**Comment by LiXingguangBrandonStark** [comment]
[Uploading [long message](base) lixi(1).pdf…]()

**Comment by LiXingguangBrandonStark** [comment]
[Uploading [long message](base) lixi(2).pdf…]()

**Comment by LiXingguangBrandonStark** [comment]
[Uploading [long message](base) lixi(3).pdf…]()

**Comment by molinav** [comment]
Under Anaconda, isn't it working if you do `conda install -c conda-forge basemap`?

**Comment by LiXingguangBrandonStark** [comment]
i use both python3 -m pip install geos, and cd geos-3.3.3
export GEOS_DIR=<where you want the libs and headers to go>
# A reasonable choice on a Unix-like system is /usr/local, or
# if you don't have permission to write there, your home directory.
./configure --prefix=$GEOS_DIR
make; make install

**Comment by LiXingguangBrandonStark** [comment]
but still not work

**Comment by LiXingguangBrandonStark** [comment]
is there anyone install basemap using mac that are worked out, thanks.

**Comment by LiXingguangBrandonStark** [comment]
@molinav can i email you, thanks. This is very important to me.

**Comment by molinav** [comment]
Sure, just write me to victor [dot] molina [at] usal [dot] es. Please pick the email since I will remove it once you write me.

**Comment by LiXingguangBrandonStark** [comment]
thanks.

**Comment by LiXingguangBrandonStark** [comment]
@molinav i have sent the email to you, if you have received my email, please let me know, this is very important to me, thanks.

**Comment by LiXingguangBrandonStark** [comment]
@metalpen1984 i used your method in mac, but still not work out when i run "python3 -m pip install ."

**Comment by LiXingguangBrandonStark** [comment]
@metalpen1984 any suggestions?

**Comment by molinav** [comment]
The problem in the end was the absence of `basemap` for Python 3.9 under Anaconda. Using a virtual environment with an older Python version (e.g. Python 3.8) was enough to install `basemap` by means of `conda` without problems.

**Comment by hydrogencl** [comment]
> @metalpen1984 i used your method in mac, but still not work out when i run "python3 -m pip install ."

Sorry for this really late reply, however my solution only works for Linux (if possible). Recently I just reinstall all the stuff on Ubuntu 20.04, and one fix should be applied since there is a ISNAN caused likely by DEBIAN/UBUNTU system: set `export CXX="g++ -std=c++98"` before installing the attached GEOS-3.3.3 in the source code.

**Comment by molinav** [comment]
@hydrogencl For your information, `basemap` version 1.3.0 is finally available in PyPI. With this version, we provide precompiled binary wheels for Windows and GNU/Linux. You can give it a try by installing as usual with `pip`:
```sh
python -m pip install basemap
```
