### ISSUE TITLE
Bad quality with python3 in bluemarble()

### ISSUE THREAD

**Issue by gcpmendez** [matplotlib/basemap#511]
I am currently running this code in python 2 and python3 and it produces an image with a different quality. In python2 it has much better quality.

Code:
from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt

map = Basemap(llcrnrlon=-10.5,llcrnrlat=33,urcrnrlon=10.,urcrnrlat=46.,
             resolution='i', projection='cass', lat_0 = 39.5, lon_0 = 0.)
map.bluemarble()
map.drawcoastlines()
plt.show()

Versions:
basemap 1.0.6/1.2.2
matplotlib 1.2.0/3.3.4

Images:
p2 - https://ibb.co/3h4pXbS
p3 - https://ibb.co/qsZ8L76

What happens?

**Comment by WeatherGod** [comment]
Most likely, the dpi settings for the files are different. Matplotlib
changed the default DPI in version 2.0, as well as the default figure size,
if I remember correctly. Indeed, the two images have different pixel
resolutions (800x600 vs. 640x480). I don't think this is a basemap issue.

**Comment by gcpmendez** [comment]
I could change the resolution with $ plt.savefig('imagen_p3.png',format='png',dpi=200) but the result it's not the same

**Comment by guziy** [comment]
Try passing the scale argument to the bluemarble method:

```
map.bluemarble(scale=2)
```

**Comment by gcpmendez** [comment]
> Try passing the scale argument to the bluemarble method:
> 
> ```
> map.bluemarble(scale=2)
> ```

not works

**Comment by molinav** [comment]
Hola @gcpmendez!

Sorry for the late reply, I was a bit busy lately and could not respond. I open the issue again because I want to take a look to it. When I find out I will write another reply.

**Comment by gcpmendez** [comment]
It's already solved

The original image in p2 have more quality that p3 in .local/lib/python3.7/site-packages/mpl_toolkits/basemap_data/bmng.jpg

After that I solved this issue:
PIL.Image.DecompressionBombError: Image size (233280000 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack
with the line:
PIL.Image.MAX_IMAGE_PIXELS = 933120000

Thank for your support
