### ISSUE TITLE
Missing half of antarctica?

### ISSUE THREAD

**Issue by jucor** [matplotlib/basemap#543]
I must be missing something obvious, but it seems that half of antarctica is missing. See e.g.
![image](https://user-images.githubusercontent.com/660037/169707240-c23791eb-80b5-47cd-ad49-4935bd54a956.png)

It used to work ™️  when I generate maps months ago, and now the same code is missing that bit of the world.

Reproduced on two machines, a Mac M1 with compilation from source and a Windows PC with installation from conda-forge's wheels, completely different environments. Any help welcome :) Thank you!

**Comment by molinav** [comment]
Hi @jucor! Yes, this is a known problem, see https://github.com/matplotlib/basemap/issues/522. The bindings to GEOS need (still) an update because something happened starting with GEOS 3.9 that sometimes is cropping the coordinates. For the moment pinning to GEOS < 3.9 should do the trick.

**Comment by jucor** [comment]
Thanks @molinav ! Not sure how to get GEOS 3.8+ with Homebrew -- looks like homebrew only has the latest version. I found the old version of the homebrew formula with 3.8 at https://github.com/Homebrew/homebrew-core/tree/cf821a26a7ca15f56d2a61a93aa9732f5b509f6f , but have no clue how to get homebrew to follow that formula (assuming it is even still working).
I realise this is beyond the scope of basemap, but would you happen to have any idea how to do that, please?

**Comment by molinav** [comment]
@jucor Unfortunately I am not expert in any of both (MacOS and Homebrew). There is always the possibility to compile GEOS from source though (having clang and cmake available in your system should be enough).

**Comment by jucor** [comment]
Thanks @molinav ! I might try that directly :) Very much appreciate your reactivity -- and your package. Thanks for all your work!

**Comment by molinav** [comment]
@jucor Just for the record, @jswhit is the author of the package, I am just the current maintainer. ;-)
