### ISSUE TITLE
Install error(s)

### ISSUE THREAD

**Issue by ktavabi** [matplotlib/basemap#551]
As per your install instructions:
`python -m pip install basemap` throws an error with Python 3.9.13, and Clang 13.1.6 (clang-1316.0.21.2.5) on darwin with GEOS installed via homebrew.

> src/_geoslib.c:745:10: fatal error: 'geos_c.h' file not found
>       #include "geos_c.h"
>                ^~~~~~~~~~
>       220 warnings and 1 error generated.
>       error: command '/usr/bin/clang' failed with exit code 1

As a matter of fact, every single one of your installation instructions throws some error.

**Comment by molinav** [comment]
Hi @ktavabi. I have a couple of questions:
- What value did you assign to the environment variable `GEOS_DIR`?
- Where is the path to the GEOS installation through Homebrew?

**Comment by molinav** [comment]
Unfortunately, without more feedback there is not much more that I can do to help. The piece of traceback is typical from not setting `GEOS_DIR` to the appropriate folder. If that is not the case, feel free to re-open this issue.
