### ISSUE TITLE
fail to install basemap in Win11 with the newest python 3.11

### ISSUE THREAD

**Issue by Fox-0124** [matplotlib/basemap#561]
When I install basemap with 'pip install basemap' or 'python -m pip install basemap', an error occurs:
![image](https://user-images.githubusercontent.com/39712328/198824639-524e09bf-f519-41bb-8cd4-3f3b8a4fa946.png)

No other python versions exist in my computer.

**Comment by molinav** [comment]
Hi @Fox-0124! Python 3.11 is relatively new, right? You are being caught by the upper pin "<3.11" in the `setup.py` file. Very likely it will be enough if I increase this upper pin and rebuild the wheels also for Python 3.11.

**Comment by molinav** [comment]
I was checking a bit further and actually `basemap` pins to `<4` as upper bound. The `<3.11` upper bound issue is coming from the build requirement `numpy==1.21.4`, because the `numpy` versions 1.21.2 to 1.21.6 added this upper bound (not present in `numpy` 1.20.x, 1.22.x or 1.23.x, for example).

**Comment by molinav** [comment]
@Fox-0124 In the end, adding the Python 3.11 support had a bit more work than expected, but the core functionality is merged into the `hotfix-1.3.6` branch. Currently, I am about to merge another Windows-related bugfix into `hotfix-1.3.6`.

When this is done, may I ask you to try out the first "pre-official" Python 3.11 wheel? Are you using Windows with Python 64-bit?

Once this issue can be closed, the `hotfix-1.3.6` branch will be finished and I will tag a new `basemap` hotfix release (1.3.6).

**Comment by molinav** [comment]
I attach you here the hotfix candidate for Windows Python 64-bit:
[basemap-1.3.6-cp311-cp311-win_amd64.zip](https://github.com/matplotlib/basemap/files/9903661/basemap-1.3.6-cp311-cp311-win_amd64.zip)

You need to change the .zip extension with .whl, otherwise I could not attach the file in the message. I made some basic tests in my computer and it seems to work. Any feedback is appreciated, I will probably release by end of the day.

**Comment by Fox-0124** [comment]
Dear @molinav , many thanks for your work. Now I success to install basemap in my computer.

**Comment by molinav** [comment]
Great to hear that! Then I will close this issue as completed.
