### ISSUE TITLE
install basemap

### ISSUE THREAD

**Issue by PPINK6518** [matplotlib/basemap#572]
i can't install basemap on anaconda.i used the command `conda install basemap`. But it's not working

**Comment by ksunden** [comment]
The matplotlib project does not maintain the conda packages, problems with installing via conda should be reported to the packagers.

It looks like basemap is should available on the `main` (i.e. the default) channel, but is also available on `conda-forge` or `anaconda`, which could potentially still work:

```
conda install -c conda-forge basemap

or

conda install -c anaconda basemap
```

While not ideal, you could also potentially install via pip (mixing conda and pip can lead to issues). If you do so, greatly recommend doing so in a conda environment.

```
conda env create -n basmapenvpip
conda activate basemapenvpip
pip install basemap
```

**Comment by PPINK6518** [comment]
thanks for your response
