### ISSUE TITLE
matplotlib < 3.7 requirement?

### ISSUE THREAD

**Issue by jameswilburlewis** [matplotlib/basemap#573]
I'm glad to see basemap is still being developed!  Are there any plans to support more recent versions of matplotlib?   We recently patched some code to remove a reference to legendHandles (now deprecated and removed from matplotlib), but this caused a version conflict with matplotlib<3.7 from basemap, and matplotlib >= 3.7 for legend_handles.   We were able to resolve the conflict with a version check, but it would be great if basemap didn't have the upper limit on matplotlib versions.

**Comment by molinav** [comment]
Hi @jameswilburlewis! In principle it should be no problem to upgrade the `matplotlib` requirements. The upper pin is there based on the latest `matplotlib` version at the time the latest `basemap` was released.

I can take a look to the requirements files in the following days to keep them up to date and release a new patch version for `basemap`.

**Comment by molinav** [comment]
The `basemap` hotfix release 1.3.7 is now available on PyPI. I will also trigger a rebuild for the `conda-forge` package soon.

I upgraded several version pins apart from `matplotlib`, you can see all the changes here: https://github.com/matplotlib/basemap/compare/v1.3.6...v1.3.7.

**Comment by molinav** [comment]
@jameswilburlewis Finally `basemap` 1.3.7 is available both on PyPI and `conda-forge` for Windows and GNU/Linux, with all the requirements up to date.

If something is still not working for you, feel free to reopen the issue and I will see what I can do.
